// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: internal/protocol/proto/common.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CardInfo 牌信息
type CardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Suit          int64                  `protobuf:"varint,1,opt,name=suit,proto3" json:"suit,omitempty"`   // 花色: 0=黑桃, 1=红心, 2=梅花, 3=方块, 4=王
	Rank          int64                  `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`   // 点数: 3-17 (3-2, 小王=16, 大王=17)
	Color         int64                  `protobuf:"varint,3,opt,name=color,proto3" json:"color,omitempty"` // 颜色: 0=黑, 1=红
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CardInfo) Reset() {
	*x = CardInfo{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CardInfo) ProtoMessage() {}

func (x *CardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CardInfo.ProtoReflect.Descriptor instead.
func (*CardInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{0}
}

func (x *CardInfo) GetSuit() int64 {
	if x != nil {
		return x.Suit
	}
	return 0
}

func (x *CardInfo) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *CardInfo) GetColor() int64 {
	if x != nil {
		return x.Color
	}
	return 0
}

// PlayerInfo 玩家信息
type PlayerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Seat          int64                  `protobuf:"varint,3,opt,name=seat,proto3" json:"seat,omitempty"`                               // 座位号 0-2
	Ready         bool                   `protobuf:"varint,4,opt,name=ready,proto3" json:"ready,omitempty"`                             // 是否准备
	IsLandlord    bool                   `protobuf:"varint,5,opt,name=is_landlord,json=isLandlord,proto3" json:"is_landlord,omitempty"` // 是否是地主
	CardsCount    int64                  `protobuf:"varint,6,opt,name=cards_count,json=cardsCount,proto3" json:"cards_count,omitempty"` // 手牌数量
	Online        bool                   `protobuf:"varint,7,opt,name=online,proto3" json:"online,omitempty"`                           // 是否在线
	IsBot         bool                   `protobuf:"varint,8,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`                // 是否是机器人
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerInfo) Reset() {
	*x = PlayerInfo{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerInfo) ProtoMessage() {}

func (x *PlayerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerInfo.ProtoReflect.Descriptor instead.
func (*PlayerInfo) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{1}
}

func (x *PlayerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PlayerInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PlayerInfo) GetSeat() int64 {
	if x != nil {
		return x.Seat
	}
	return 0
}

func (x *PlayerInfo) GetReady() bool {
	if x != nil {
		return x.Ready
	}
	return false
}

func (x *PlayerInfo) GetIsLandlord() bool {
	if x != nil {
		return x.IsLandlord
	}
	return false
}

func (x *PlayerInfo) GetCardsCount() int64 {
	if x != nil {
		return x.CardsCount
	}
	return 0
}

func (x *PlayerInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PlayerInfo) GetIsBot() bool {
	if x != nil {
		return x.IsBot
	}
	return false
}

// PlayerPlayedCards 某位玩家本局已经公开打出的牌
type PlayerPlayedCards struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Cards         []*CardInfo            `protobuf:"bytes,2,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerPlayedCards) Reset() {
	*x = PlayerPlayedCards{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerPlayedCards) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerPlayedCards) ProtoMessage() {}

func (x *PlayerPlayedCards) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerPlayedCards.ProtoReflect.Descriptor instead.
func (*PlayerPlayedCards) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{2}
}

func (x *PlayerPlayedCards) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerPlayedCards) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

// PlayerHand 玩家手牌信息（用于游戏结束展示）
type PlayerHand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Cards         []*CardInfo            `protobuf:"bytes,3,rep,name=cards,proto3" json:"cards,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerHand) Reset() {
	*x = PlayerHand{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerHand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerHand) ProtoMessage() {}

func (x *PlayerHand) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerHand.ProtoReflect.Descriptor instead.
func (*PlayerHand) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{3}
}

func (x *PlayerHand) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerHand) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerHand) GetCards() []*CardInfo {
	if x != nil {
		return x.Cards
	}
	return nil
}

// PlayerScore 玩家本局得分（用于游戏结束结算）
type PlayerScore struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	IsLandlord    bool                   `protobuf:"varint,3,opt,name=is_landlord,json=isLandlord,proto3" json:"is_landlord,omitempty"` // 是否是地主
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`                             // 本局得分（输为负，赢为正）
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerScore) Reset() {
	*x = PlayerScore{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerScore) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerScore) ProtoMessage() {}

func (x *PlayerScore) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerScore.ProtoReflect.Descriptor instead.
func (*PlayerScore) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{4}
}

func (x *PlayerScore) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerScore) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerScore) GetIsLandlord() bool {
	if x != nil {
		return x.IsLandlord
	}
	return false
}

func (x *PlayerScore) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

// GameStateDTO 游戏状态数据传输对象（用于重连恢复）
type GameStateDTO struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	Phase               string                 `protobuf:"bytes,1,opt,name=phase,proto3" json:"phase,omitempty"`                                                            // waiting/bidding/playing/ended
	Players             []*PlayerInfo          `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`                                                        // 所有玩家信息
	Hand                []*CardInfo            `protobuf:"bytes,3,rep,name=hand,proto3" json:"hand,omitempty"`                                                              // 自己的手牌
	BottomCards         []*CardInfo            `protobuf:"bytes,4,rep,name=bottom_cards,json=bottomCards,proto3" json:"bottom_cards,omitempty"`                             // 已公开的底牌
	CurrentTurn         string                 `protobuf:"bytes,5,opt,name=current_turn,json=currentTurn,proto3" json:"current_turn,omitempty"`                             // 当前回合玩家 ID
	LastPlayed          []*CardInfo            `protobuf:"bytes,6,rep,name=last_played,json=lastPlayed,proto3" json:"last_played,omitempty"`                                // 上家出的牌
	LastPlayerId        string                 `protobuf:"bytes,7,opt,name=last_player_id,json=lastPlayerId,proto3" json:"last_player_id,omitempty"`                        // 上家 ID
	MustPlay            bool                   `protobuf:"varint,8,opt,name=must_play,json=mustPlay,proto3" json:"must_play,omitempty"`                                     // 是否必须出牌
	CanBeat             bool                   `protobuf:"varint,9,opt,name=can_beat,json=canBeat,proto3" json:"can_beat,omitempty"`                                        // 是否能打过
	SnapshotVersion     int64                  `protobuf:"varint,10,opt,name=snapshot_version,json=snapshotVersion,proto3" json:"snapshot_version,omitempty"`               // 单调递增的快照/事件版本
	GameId              string                 `protobuf:"bytes,11,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                                           // 当前牌局 ID
	BottomCardsRevealed bool                   `protobuf:"varint,12,opt,name=bottom_cards_revealed,json=bottomCardsRevealed,proto3" json:"bottom_cards_revealed,omitempty"` // 底牌是否已经公开
	TurnId              int64                  `protobuf:"varint,13,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`                                          // 当前回合序号
	TurnDeadlineMs      int64                  `protobuf:"varint,14,opt,name=turn_deadline_ms,json=turnDeadlineMs,proto3" json:"turn_deadline_ms,omitempty"`                // 服务端绝对截止时间
	ServerTimeMs        int64                  `protobuf:"varint,15,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`                      // 生成快照时的服务端时间
	LastPlayerName      string                 `protobuf:"bytes,16,opt,name=last_player_name,json=lastPlayerName,proto3" json:"last_player_name,omitempty"`                 // 有效上一手玩家名称
	LastHandType        string                 `protobuf:"bytes,17,opt,name=last_hand_type,json=lastHandType,proto3" json:"last_hand_type,omitempty"`                       // 有效上一手牌型
	IsGrab              bool                   `protobuf:"varint,18,opt,name=is_grab,json=isGrab,proto3" json:"is_grab,omitempty"`                                          // 是否处于抢地主阶段
	Multiplier          int64                  `protobuf:"varint,19,opt,name=multiplier,proto3" json:"multiplier,omitempty"`                                                // 当前倍数
	BaseScore           int64                  `protobuf:"varint,20,opt,name=base_score,json=baseScore,proto3" json:"base_score,omitempty"`                                 // 本局底分
	PlayedCards         []*PlayerPlayedCards   `protobuf:"bytes,21,rep,name=played_cards,json=playedCards,proto3" json:"played_cards,omitempty"`                            // 已公开出牌账本
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GameStateDTO) Reset() {
	*x = GameStateDTO{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateDTO) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateDTO) ProtoMessage() {}

func (x *GameStateDTO) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateDTO.ProtoReflect.Descriptor instead.
func (*GameStateDTO) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{5}
}

func (x *GameStateDTO) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *GameStateDTO) GetPlayers() []*PlayerInfo {
	if x != nil {
		return x.Players
	}
	return nil
}

func (x *GameStateDTO) GetHand() []*CardInfo {
	if x != nil {
		return x.Hand
	}
	return nil
}

func (x *GameStateDTO) GetBottomCards() []*CardInfo {
	if x != nil {
		return x.BottomCards
	}
	return nil
}

func (x *GameStateDTO) GetCurrentTurn() string {
	if x != nil {
		return x.CurrentTurn
	}
	return ""
}

func (x *GameStateDTO) GetLastPlayed() []*CardInfo {
	if x != nil {
		return x.LastPlayed
	}
	return nil
}

func (x *GameStateDTO) GetLastPlayerId() string {
	if x != nil {
		return x.LastPlayerId
	}
	return ""
}

func (x *GameStateDTO) GetMustPlay() bool {
	if x != nil {
		return x.MustPlay
	}
	return false
}

func (x *GameStateDTO) GetCanBeat() bool {
	if x != nil {
		return x.CanBeat
	}
	return false
}

func (x *GameStateDTO) GetSnapshotVersion() int64 {
	if x != nil {
		return x.SnapshotVersion
	}
	return 0
}

func (x *GameStateDTO) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *GameStateDTO) GetBottomCardsRevealed() bool {
	if x != nil {
		return x.BottomCardsRevealed
	}
	return false
}

func (x *GameStateDTO) GetTurnId() int64 {
	if x != nil {
		return x.TurnId
	}
	return 0
}

func (x *GameStateDTO) GetTurnDeadlineMs() int64 {
	if x != nil {
		return x.TurnDeadlineMs
	}
	return 0
}

func (x *GameStateDTO) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *GameStateDTO) GetLastPlayerName() string {
	if x != nil {
		return x.LastPlayerName
	}
	return ""
}

func (x *GameStateDTO) GetLastHandType() string {
	if x != nil {
		return x.LastHandType
	}
	return ""
}

func (x *GameStateDTO) GetIsGrab() bool {
	if x != nil {
		return x.IsGrab
	}
	return false
}

func (x *GameStateDTO) GetMultiplier() int64 {
	if x != nil {
		return x.Multiplier
	}
	return 0
}

func (x *GameStateDTO) GetBaseScore() int64 {
	if x != nil {
		return x.BaseScore
	}
	return 0
}

func (x *GameStateDTO) GetPlayedCards() []*PlayerPlayedCards {
	if x != nil {
		return x.PlayedCards
	}
	return nil
}

// ChatPayload 聊天请求和服务端聊天事件的统一协议。
// 字段 1-6 与早期 Web JSON contract 保持一致；新增字段由服务端确认。
type ChatPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SenderId      string                 `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	SenderName    string                 `protobuf:"bytes,2,opt,name=sender_name,json=senderName,proto3" json:"sender_name,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Scope         string                 `protobuf:"bytes,4,opt,name=scope,proto3" json:"scope,omitempty"` // lobby/room/game
	Time          int64                  `protobuf:"varint,5,opt,name=time,proto3" json:"time,omitempty"`  // 兼容字段，Unix 秒
	IsSystem      bool                   `protobuf:"varint,6,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	MessageId     string                 `protobuf:"bytes,7,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	RoomCode      string                 `protobuf:"bytes,8,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	GameId        string                 `protobuf:"bytes,9,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	ServerTime    int64                  `protobuf:"varint,10,opt,name=server_time,json=serverTime,proto3" json:"server_time,omitempty"` // Unix 毫秒
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatPayload) Reset() {
	*x = ChatPayload{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatPayload) ProtoMessage() {}

func (x *ChatPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatPayload.ProtoReflect.Descriptor instead.
func (*ChatPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{6}
}

func (x *ChatPayload) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChatPayload) GetSenderName() string {
	if x != nil {
		return x.SenderName
	}
	return ""
}

func (x *ChatPayload) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChatPayload) GetScope() string {
	if x != nil {
		return x.Scope
	}
	return ""
}

func (x *ChatPayload) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *ChatPayload) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *ChatPayload) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChatPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *ChatPayload) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *ChatPayload) GetServerTime() int64 {
	if x != nil {
		return x.ServerTime
	}
	return 0
}

// LeaderboardEntry 排行榜条目
type LeaderboardEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rank          int64                  `protobuf:"varint,1,opt,name=rank,proto3" json:"rank,omitempty"`
	PlayerId      string                 `protobuf:"bytes,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,3,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Score         int64                  `protobuf:"varint,4,opt,name=score,proto3" json:"score,omitempty"`
	Wins          int64                  `protobuf:"varint,5,opt,name=wins,proto3" json:"wins,omitempty"`
	WinRate       float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardEntry) Reset() {
	*x = LeaderboardEntry{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardEntry) ProtoMessage() {}

func (x *LeaderboardEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardEntry.ProtoReflect.Descriptor instead.
func (*LeaderboardEntry) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{7}
}

func (x *LeaderboardEntry) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *LeaderboardEntry) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *LeaderboardEntry) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *LeaderboardEntry) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *LeaderboardEntry) GetWins() int64 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *LeaderboardEntry) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

// RoomListItem 房间列表项
type RoomListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	PlayerCount   int64                  `protobuf:"varint,2,opt,name=player_count,json=playerCount,proto3" json:"player_count,omitempty"`
	MaxPlayers    int64                  `protobuf:"varint,3,opt,name=max_players,json=maxPlayers,proto3" json:"max_players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListItem) Reset() {
	*x = RoomListItem{}
	mi := &file_internal_protocol_proto_common_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListItem) ProtoMessage() {}

func (x *RoomListItem) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_common_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListItem.ProtoReflect.Descriptor instead.
func (*RoomListItem) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_common_proto_rawDescGZIP(), []int{8}
}

func (x *RoomListItem) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *RoomListItem) GetPlayerCount() int64 {
	if x != nil {
		return x.PlayerCount
	}
	return 0
}

func (x *RoomListItem) GetMaxPlayers() int64 {
	if x != nil {
		return x.MaxPlayers
	}
	return 0
}

var File_internal_protocol_proto_common_proto protoreflect.FileDescriptor

const file_internal_protocol_proto_common_proto_rawDesc = "" +
	"\n" +
	"$internal/protocol/proto/common.proto\x12\bprotocol\"H\n" +
	"\bCardInfo\x12\x12\n" +
	"\x04suit\x18\x01 \x01(\x03R\x04suit\x12\x12\n" +
	"\x04rank\x18\x02 \x01(\x03R\x04rank\x12\x14\n" +
	"\x05color\x18\x03 \x01(\x03R\x05color\"\xcb\x01\n" +
	"\n" +
	"PlayerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04seat\x18\x03 \x01(\x03R\x04seat\x12\x14\n" +
	"\x05ready\x18\x04 \x01(\bR\x05ready\x12\x1f\n" +
	"\vis_landlord\x18\x05 \x01(\bR\n" +
	"isLandlord\x12\x1f\n" +
	"\vcards_count\x18\x06 \x01(\x03R\n" +
	"cardsCount\x12\x16\n" +
	"\x06online\x18\a \x01(\bR\x06online\x12\x15\n" +
	"\x06is_bot\x18\b \x01(\bR\x05isBot\"Z\n" +
	"\x11PlayerPlayedCards\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12(\n" +
	"\x05cards\x18\x02 \x03(\v2\x12.protocol.CardInfoR\x05cards\"t\n" +
	"\n" +
	"PlayerHand\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12(\n" +
	"\x05cards\x18\x03 \x03(\v2\x12.protocol.CardInfoR\x05cards\"\x82\x01\n" +
	"\vPlayerScore\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vis_landlord\x18\x03 \x01(\bR\n" +
	"isLandlord\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\"\xb2\x06\n" +
	"\fGameStateDTO\x12\x14\n" +
	"\x05phase\x18\x01 \x01(\tR\x05phase\x12.\n" +
	"\aplayers\x18\x02 \x03(\v2\x14.protocol.PlayerInfoR\aplayers\x12&\n" +
	"\x04hand\x18\x03 \x03(\v2\x12.protocol.CardInfoR\x04hand\x125\n" +
	"\fbottom_cards\x18\x04 \x03(\v2\x12.protocol.CardInfoR\vbottomCards\x12!\n" +
	"\fcurrent_turn\x18\x05 \x01(\tR\vcurrentTurn\x123\n" +
	"\vlast_played\x18\x06 \x03(\v2\x12.protocol.CardInfoR\n" +
	"lastPlayed\x12$\n" +
	"\x0elast_player_id\x18\a \x01(\tR\flastPlayerId\x12\x1b\n" +
	"\tmust_play\x18\b \x01(\bR\bmustPlay\x12\x19\n" +
	"\bcan_beat\x18\t \x01(\bR\acanBeat\x12)\n" +
	"\x10snapshot_version\x18\n" +
	" \x01(\x03R\x0fsnapshotVersion\x12\x17\n" +
	"\agame_id\x18\v \x01(\tR\x06gameId\x122\n" +
	"\x15bottom_cards_revealed\x18\f \x01(\bR\x13bottomCardsRevealed\x12\x17\n" +
	"\aturn_id\x18\r \x01(\x03R\x06turnId\x12(\n" +
	"\x10turn_deadline_ms\x18\x0e \x01(\x03R\x0eturnDeadlineMs\x12$\n" +
	"\x0eserver_time_ms\x18\x0f \x01(\x03R\fserverTimeMs\x12(\n" +
	"\x10last_player_name\x18\x10 \x01(\tR\x0elastPlayerName\x12$\n" +
	"\x0elast_hand_type\x18\x11 \x01(\tR\flastHandType\x12\x17\n" +
	"\ais_grab\x18\x12 \x01(\bR\x06isGrab\x12\x1e\n" +
	"\n" +
	"multiplier\x18\x13 \x01(\x03R\n" +
	"multiplier\x12\x1d\n" +
	"\n" +
	"base_score\x18\x14 \x01(\x03R\tbaseScore\x12>\n" +
	"\fplayed_cards\x18\x15 \x03(\v2\x1b.protocol.PlayerPlayedCardsR\vplayedCards\"\xa2\x02\n" +
	"\vChatPayload\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\tR\bsenderId\x12\x1f\n" +
	"\vsender_name\x18\x02 \x01(\tR\n" +
	"senderName\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x14\n" +
	"\x05scope\x18\x04 \x01(\tR\x05scope\x12\x12\n" +
	"\x04time\x18\x05 \x01(\x03R\x04time\x12\x1b\n" +
	"\tis_system\x18\x06 \x01(\bR\bisSystem\x12\x1d\n" +
	"\n" +
	"message_id\x18\a \x01(\tR\tmessageId\x12\x1b\n" +
	"\troom_code\x18\b \x01(\tR\broomCode\x12\x17\n" +
	"\agame_id\x18\t \x01(\tR\x06gameId\x12\x1f\n" +
	"\vserver_time\x18\n" +
	" \x01(\x03R\n" +
	"serverTime\"\xa9\x01\n" +
	"\x10LeaderboardEntry\x12\x12\n" +
	"\x04rank\x18\x01 \x01(\x03R\x04rank\x12\x1b\n" +
	"\tplayer_id\x18\x02 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x03 \x01(\tR\n" +
	"playerName\x12\x14\n" +
	"\x05score\x18\x04 \x01(\x03R\x05score\x12\x12\n" +
	"\x04wins\x18\x05 \x01(\x03R\x04wins\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\"o\n" +
	"\fRoomListItem\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\x12!\n" +
	"\fplayer_count\x18\x02 \x01(\x03R\vplayerCount\x12\x1f\n" +
	"\vmax_players\x18\x03 \x01(\x03R\n" +
	"maxPlayersB=Z;github.com/palemoky/fight-the-landlord/internal/protocol/pbb\x06proto3"

var (
	file_internal_protocol_proto_common_proto_rawDescOnce sync.Once
	file_internal_protocol_proto_common_proto_rawDescData []byte
)

func file_internal_protocol_proto_common_proto_rawDescGZIP() []byte {
	file_internal_protocol_proto_common_proto_rawDescOnce.Do(func() {
		file_internal_protocol_proto_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_common_proto_rawDesc), len(file_internal_protocol_proto_common_proto_rawDesc)))
	})
	return file_internal_protocol_proto_common_proto_rawDescData
}

var file_internal_protocol_proto_common_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_internal_protocol_proto_common_proto_goTypes = []any{
	(*CardInfo)(nil),          // 0: protocol.CardInfo
	(*PlayerInfo)(nil),        // 1: protocol.PlayerInfo
	(*PlayerPlayedCards)(nil), // 2: protocol.PlayerPlayedCards
	(*PlayerHand)(nil),        // 3: protocol.PlayerHand
	(*PlayerScore)(nil),       // 4: protocol.PlayerScore
	(*GameStateDTO)(nil),      // 5: protocol.GameStateDTO
	(*ChatPayload)(nil),       // 6: protocol.ChatPayload
	(*LeaderboardEntry)(nil),  // 7: protocol.LeaderboardEntry
	(*RoomListItem)(nil),      // 8: protocol.RoomListItem
}
var file_internal_protocol_proto_common_proto_depIdxs = []int32{
	0, // 0: protocol.PlayerPlayedCards.cards:type_name -> protocol.CardInfo
	0, // 1: protocol.PlayerHand.cards:type_name -> protocol.CardInfo
	1, // 2: protocol.GameStateDTO.players:type_name -> protocol.PlayerInfo
	0, // 3: protocol.GameStateDTO.hand:type_name -> protocol.CardInfo
	0, // 4: protocol.GameStateDTO.bottom_cards:type_name -> protocol.CardInfo
	0, // 5: protocol.GameStateDTO.last_played:type_name -> protocol.CardInfo
	2, // 6: protocol.GameStateDTO.played_cards:type_name -> protocol.PlayerPlayedCards
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_internal_protocol_proto_common_proto_init() }
func file_internal_protocol_proto_common_proto_init() {
	if File_internal_protocol_proto_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_common_proto_rawDesc), len(file_internal_protocol_proto_common_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_proto_common_proto_goTypes,
		DependencyIndexes: file_internal_protocol_proto_common_proto_depIdxs,
		MessageInfos:      file_internal_protocol_proto_common_proto_msgTypes,
	}.Build()
	File_internal_protocol_proto_common_proto = out.File
	file_internal_protocol_proto_common_proto_goTypes = nil
	file_internal_protocol_proto_common_proto_depIdxs = nil
}
