// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: internal/protocol/proto/message.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MessageType int32

const (
	MessageType_MSG_UNKNOWN MessageType = 0
	// 客户端 -> 服务端
	MessageType_MSG_RECONNECT              MessageType = 1
	MessageType_MSG_PING                   MessageType = 2
	MessageType_MSG_CREATE_ROOM            MessageType = 3
	MessageType_MSG_JOIN_ROOM              MessageType = 4
	MessageType_MSG_LEAVE_ROOM             MessageType = 5
	MessageType_MSG_QUICK_MATCH            MessageType = 6
	MessageType_MSG_READY                  MessageType = 7
	MessageType_MSG_CANCEL_READY           MessageType = 8
	MessageType_MSG_BID                    MessageType = 9
	MessageType_MSG_PLAY_CARDS             MessageType = 10
	MessageType_MSG_PASS                   MessageType = 11
	MessageType_MSG_GET_STATS              MessageType = 12
	MessageType_MSG_GET_LEADERBOARD        MessageType = 13
	MessageType_MSG_GET_ROOM_LIST          MessageType = 14
	MessageType_MSG_GET_ONLINE_COUNT       MessageType = 15
	MessageType_MSG_CHAT                   MessageType = 16
	MessageType_MSG_GET_MAINTENANCE_STATUS MessageType = 17
	MessageType_MSG_CANCEL_MATCH           MessageType = 18
	// 服务端 -> 客户端
	MessageType_MSG_CONNECTED          MessageType = 100
	MessageType_MSG_RECONNECTED        MessageType = 101
	MessageType_MSG_PONG               MessageType = 102
	MessageType_MSG_PLAYER_OFFLINE     MessageType = 103
	MessageType_MSG_PLAYER_ONLINE      MessageType = 104
	MessageType_MSG_ONLINE_COUNT       MessageType = 105
	MessageType_MSG_ROOM_CREATED       MessageType = 106
	MessageType_MSG_ROOM_JOINED        MessageType = 107
	MessageType_MSG_PLAYER_JOINED      MessageType = 108
	MessageType_MSG_PLAYER_LEFT        MessageType = 109
	MessageType_MSG_PLAYER_READY       MessageType = 110
	MessageType_MSG_MATCH_FOUND        MessageType = 111
	MessageType_MSG_GAME_START         MessageType = 112
	MessageType_MSG_DEAL_CARDS         MessageType = 113
	MessageType_MSG_BID_TURN           MessageType = 114
	MessageType_MSG_BID_RESULT         MessageType = 115
	MessageType_MSG_LANDLORD           MessageType = 116
	MessageType_MSG_PLAY_TURN          MessageType = 117
	MessageType_MSG_CARD_PLAYED        MessageType = 118
	MessageType_MSG_PLAYER_PASS        MessageType = 119
	MessageType_MSG_GAME_OVER          MessageType = 120
	MessageType_MSG_ROUND_RESULT       MessageType = 121
	MessageType_MSG_STATS_RESULT       MessageType = 122
	MessageType_MSG_LEADERBOARD_RESULT MessageType = 123
	MessageType_MSG_ROOM_LIST_RESULT   MessageType = 124
	MessageType_MSG_MAINTENANCE_STATUS MessageType = 125
	MessageType_MSG_MAINTENANCE        MessageType = 126
	MessageType_MSG_MATCH_QUEUED       MessageType = 127
	MessageType_MSG_MATCH_CANCELLED    MessageType = 128
	MessageType_MSG_ROOM_LEFT          MessageType = 129
	MessageType_MSG_ERROR              MessageType = 200
	MessageType_MSG_PRACTICE_MATCH     MessageType = 201
)

// Enum value maps for MessageType.
var (
	MessageType_name = map[int32]string{
		0:   "MSG_UNKNOWN",
		1:   "MSG_RECONNECT",
		2:   "MSG_PING",
		3:   "MSG_CREATE_ROOM",
		4:   "MSG_JOIN_ROOM",
		5:   "MSG_LEAVE_ROOM",
		6:   "MSG_QUICK_MATCH",
		7:   "MSG_READY",
		8:   "MSG_CANCEL_READY",
		9:   "MSG_BID",
		10:  "MSG_PLAY_CARDS",
		11:  "MSG_PASS",
		12:  "MSG_GET_STATS",
		13:  "MSG_GET_LEADERBOARD",
		14:  "MSG_GET_ROOM_LIST",
		15:  "MSG_GET_ONLINE_COUNT",
		16:  "MSG_CHAT",
		17:  "MSG_GET_MAINTENANCE_STATUS",
		18:  "MSG_CANCEL_MATCH",
		100: "MSG_CONNECTED",
		101: "MSG_RECONNECTED",
		102: "MSG_PONG",
		103: "MSG_PLAYER_OFFLINE",
		104: "MSG_PLAYER_ONLINE",
		105: "MSG_ONLINE_COUNT",
		106: "MSG_ROOM_CREATED",
		107: "MSG_ROOM_JOINED",
		108: "MSG_PLAYER_JOINED",
		109: "MSG_PLAYER_LEFT",
		110: "MSG_PLAYER_READY",
		111: "MSG_MATCH_FOUND",
		112: "MSG_GAME_START",
		113: "MSG_DEAL_CARDS",
		114: "MSG_BID_TURN",
		115: "MSG_BID_RESULT",
		116: "MSG_LANDLORD",
		117: "MSG_PLAY_TURN",
		118: "MSG_CARD_PLAYED",
		119: "MSG_PLAYER_PASS",
		120: "MSG_GAME_OVER",
		121: "MSG_ROUND_RESULT",
		122: "MSG_STATS_RESULT",
		123: "MSG_LEADERBOARD_RESULT",
		124: "MSG_ROOM_LIST_RESULT",
		125: "MSG_MAINTENANCE_STATUS",
		126: "MSG_MAINTENANCE",
		127: "MSG_MATCH_QUEUED",
		128: "MSG_MATCH_CANCELLED",
		129: "MSG_ROOM_LEFT",
		200: "MSG_ERROR",
		201: "MSG_PRACTICE_MATCH",
	}
	MessageType_value = map[string]int32{
		"MSG_UNKNOWN":                0,
		"MSG_RECONNECT":              1,
		"MSG_PING":                   2,
		"MSG_CREATE_ROOM":            3,
		"MSG_JOIN_ROOM":              4,
		"MSG_LEAVE_ROOM":             5,
		"MSG_QUICK_MATCH":            6,
		"MSG_READY":                  7,
		"MSG_CANCEL_READY":           8,
		"MSG_BID":                    9,
		"MSG_PLAY_CARDS":             10,
		"MSG_PASS":                   11,
		"MSG_GET_STATS":              12,
		"MSG_GET_LEADERBOARD":        13,
		"MSG_GET_ROOM_LIST":          14,
		"MSG_GET_ONLINE_COUNT":       15,
		"MSG_CHAT":                   16,
		"MSG_GET_MAINTENANCE_STATUS": 17,
		"MSG_CANCEL_MATCH":           18,
		"MSG_CONNECTED":              100,
		"MSG_RECONNECTED":            101,
		"MSG_PONG":                   102,
		"MSG_PLAYER_OFFLINE":         103,
		"MSG_PLAYER_ONLINE":          104,
		"MSG_ONLINE_COUNT":           105,
		"MSG_ROOM_CREATED":           106,
		"MSG_ROOM_JOINED":            107,
		"MSG_PLAYER_JOINED":          108,
		"MSG_PLAYER_LEFT":            109,
		"MSG_PLAYER_READY":           110,
		"MSG_MATCH_FOUND":            111,
		"MSG_GAME_START":             112,
		"MSG_DEAL_CARDS":             113,
		"MSG_BID_TURN":               114,
		"MSG_BID_RESULT":             115,
		"MSG_LANDLORD":               116,
		"MSG_PLAY_TURN":              117,
		"MSG_CARD_PLAYED":            118,
		"MSG_PLAYER_PASS":            119,
		"MSG_GAME_OVER":              120,
		"MSG_ROUND_RESULT":           121,
		"MSG_STATS_RESULT":           122,
		"MSG_LEADERBOARD_RESULT":     123,
		"MSG_ROOM_LIST_RESULT":       124,
		"MSG_MAINTENANCE_STATUS":     125,
		"MSG_MAINTENANCE":            126,
		"MSG_MATCH_QUEUED":           127,
		"MSG_MATCH_CANCELLED":        128,
		"MSG_ROOM_LEFT":              129,
		"MSG_ERROR":                  200,
		"MSG_PRACTICE_MATCH":         201,
	}
)

func (x MessageType) Enum() *MessageType {
	p := new(MessageType)
	*p = x
	return p
}

func (x MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_protocol_proto_message_proto_enumTypes[0].Descriptor()
}

func (MessageType) Type() protoreflect.EnumType {
	return &file_internal_protocol_proto_message_proto_enumTypes[0]
}

func (x MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MessageType.Descriptor instead.
func (MessageType) EnumDescriptor() ([]byte, []int) {
	return file_internal_protocol_proto_message_proto_rawDescGZIP(), []int{0}
}

// EventMeta 权威服务端事件的顺序与计时上下文。
// 旧客户端会按 protobuf 规则忽略该可选字段。
type EventMeta struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	StreamId       string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`                      // game:<game_id> 或其他服务端事件流
	EventVersion   int64                  `protobuf:"varint,2,opt,name=event_version,json=eventVersion,proto3" json:"event_version,omitempty"`         // 流内单调递增的权威事件水位
	GameId         string                 `protobuf:"bytes,3,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`                            // 牌局 ID；非牌局事件可为空
	TurnId         int64                  `protobuf:"varint,4,opt,name=turn_id,json=turnId,proto3" json:"turn_id,omitempty"`                           // 当前回合序号
	ServerTimeMs   int64                  `protobuf:"varint,5,opt,name=server_time_ms,json=serverTimeMs,proto3" json:"server_time_ms,omitempty"`       // 生成事件时的服务端 Unix 毫秒
	TurnDeadlineMs int64                  `protobuf:"varint,6,opt,name=turn_deadline_ms,json=turnDeadlineMs,proto3" json:"turn_deadline_ms,omitempty"` // 当前回合的服务端绝对截止时间
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EventMeta) Reset() {
	*x = EventMeta{}
	mi := &file_internal_protocol_proto_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventMeta) ProtoMessage() {}

func (x *EventMeta) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventMeta.ProtoReflect.Descriptor instead.
func (*EventMeta) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_message_proto_rawDescGZIP(), []int{0}
}

func (x *EventMeta) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *EventMeta) GetEventVersion() int64 {
	if x != nil {
		return x.EventVersion
	}
	return 0
}

func (x *EventMeta) GetGameId() string {
	if x != nil {
		return x.GameId
	}
	return ""
}

func (x *EventMeta) GetTurnId() int64 {
	if x != nil {
		return x.TurnId
	}
	return 0
}

func (x *EventMeta) GetServerTimeMs() int64 {
	if x != nil {
		return x.ServerTimeMs
	}
	return 0
}

func (x *EventMeta) GetTurnDeadlineMs() int64 {
	if x != nil {
		return x.TurnDeadlineMs
	}
	return 0
}

// Message 所有消息的外层包装
type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          MessageType            `protobuf:"varint,1,opt,name=type,proto3,enum=protocol.MessageType" json:"type,omitempty"`
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Event         *EventMeta             `protobuf:"bytes,3,opt,name=event,proto3" json:"event,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_internal_protocol_proto_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_message_proto_rawDescGZIP(), []int{1}
}

func (x *Message) GetType() MessageType {
	if x != nil {
		return x.Type
	}
	return MessageType_MSG_UNKNOWN
}

func (x *Message) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *Message) GetEvent() *EventMeta {
	if x != nil {
		return x.Event
	}
	return nil
}

var File_internal_protocol_proto_message_proto protoreflect.FileDescriptor

const file_internal_protocol_proto_message_proto_rawDesc = "" +
	"\n" +
	"%internal/protocol/proto/message.proto\x12\bprotocol\"\xcf\x01\n" +
	"\tEventMeta\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12#\n" +
	"\revent_version\x18\x02 \x01(\x03R\feventVersion\x12\x17\n" +
	"\agame_id\x18\x03 \x01(\tR\x06gameId\x12\x17\n" +
	"\aturn_id\x18\x04 \x01(\x03R\x06turnId\x12$\n" +
	"\x0eserver_time_ms\x18\x05 \x01(\x03R\fserverTimeMs\x12(\n" +
	"\x10turn_deadline_ms\x18\x06 \x01(\x03R\x0eturnDeadlineMs\"y\n" +
	"\aMessage\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.protocol.MessageTypeR\x04type\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12)\n" +
	"\x05event\x18\x03 \x01(\v2\x13.protocol.EventMetaR\x05event*\xb2\b\n" +
	"\vMessageType\x12\x0f\n" +
	"\vMSG_UNKNOWN\x10\x00\x12\x11\n" +
	"\rMSG_RECONNECT\x10\x01\x12\f\n" +
	"\bMSG_PING\x10\x02\x12\x13\n" +
	"\x0fMSG_CREATE_ROOM\x10\x03\x12\x11\n" +
	"\rMSG_JOIN_ROOM\x10\x04\x12\x12\n" +
	"\x0eMSG_LEAVE_ROOM\x10\x05\x12\x13\n" +
	"\x0fMSG_QUICK_MATCH\x10\x06\x12\r\n" +
	"\tMSG_READY\x10\a\x12\x14\n" +
	"\x10MSG_CANCEL_READY\x10\b\x12\v\n" +
	"\aMSG_BID\x10\t\x12\x12\n" +
	"\x0eMSG_PLAY_CARDS\x10\n" +
	"\x12\f\n" +
	"\bMSG_PASS\x10\v\x12\x11\n" +
	"\rMSG_GET_STATS\x10\f\x12\x17\n" +
	"\x13MSG_GET_LEADERBOARD\x10\r\x12\x15\n" +
	"\x11MSG_GET_ROOM_LIST\x10\x0e\x12\x18\n" +
	"\x14MSG_GET_ONLINE_COUNT\x10\x0f\x12\f\n" +
	"\bMSG_CHAT\x10\x10\x12\x1e\n" +
	"\x1aMSG_GET_MAINTENANCE_STATUS\x10\x11\x12\x14\n" +
	"\x10MSG_CANCEL_MATCH\x10\x12\x12\x11\n" +
	"\rMSG_CONNECTED\x10d\x12\x13\n" +
	"\x0fMSG_RECONNECTED\x10e\x12\f\n" +
	"\bMSG_PONG\x10f\x12\x16\n" +
	"\x12MSG_PLAYER_OFFLINE\x10g\x12\x15\n" +
	"\x11MSG_PLAYER_ONLINE\x10h\x12\x14\n" +
	"\x10MSG_ONLINE_COUNT\x10i\x12\x14\n" +
	"\x10MSG_ROOM_CREATED\x10j\x12\x13\n" +
	"\x0fMSG_ROOM_JOINED\x10k\x12\x15\n" +
	"\x11MSG_PLAYER_JOINED\x10l\x12\x13\n" +
	"\x0fMSG_PLAYER_LEFT\x10m\x12\x14\n" +
	"\x10MSG_PLAYER_READY\x10n\x12\x13\n" +
	"\x0fMSG_MATCH_FOUND\x10o\x12\x12\n" +
	"\x0eMSG_GAME_START\x10p\x12\x12\n" +
	"\x0eMSG_DEAL_CARDS\x10q\x12\x10\n" +
	"\fMSG_BID_TURN\x10r\x12\x12\n" +
	"\x0eMSG_BID_RESULT\x10s\x12\x10\n" +
	"\fMSG_LANDLORD\x10t\x12\x11\n" +
	"\rMSG_PLAY_TURN\x10u\x12\x13\n" +
	"\x0fMSG_CARD_PLAYED\x10v\x12\x13\n" +
	"\x0fMSG_PLAYER_PASS\x10w\x12\x11\n" +
	"\rMSG_GAME_OVER\x10x\x12\x14\n" +
	"\x10MSG_ROUND_RESULT\x10y\x12\x14\n" +
	"\x10MSG_STATS_RESULT\x10z\x12\x1a\n" +
	"\x16MSG_LEADERBOARD_RESULT\x10{\x12\x18\n" +
	"\x14MSG_ROOM_LIST_RESULT\x10|\x12\x1a\n" +
	"\x16MSG_MAINTENANCE_STATUS\x10}\x12\x13\n" +
	"\x0fMSG_MAINTENANCE\x10~\x12\x14\n" +
	"\x10MSG_MATCH_QUEUED\x10\x7f\x12\x18\n" +
	"\x13MSG_MATCH_CANCELLED\x10\x80\x01\x12\x12\n" +
	"\rMSG_ROOM_LEFT\x10\x81\x01\x12\x0e\n" +
	"\tMSG_ERROR\x10\xc8\x01\x12\x17\n" +
	"\x12MSG_PRACTICE_MATCH\x10\xc9\x01B=Z;github.com/palemoky/fight-the-landlord/internal/protocol/pbb\x06proto3"

var (
	file_internal_protocol_proto_message_proto_rawDescOnce sync.Once
	file_internal_protocol_proto_message_proto_rawDescData []byte
)

func file_internal_protocol_proto_message_proto_rawDescGZIP() []byte {
	file_internal_protocol_proto_message_proto_rawDescOnce.Do(func() {
		file_internal_protocol_proto_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_message_proto_rawDesc), len(file_internal_protocol_proto_message_proto_rawDesc)))
	})
	return file_internal_protocol_proto_message_proto_rawDescData
}

var file_internal_protocol_proto_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_protocol_proto_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_protocol_proto_message_proto_goTypes = []any{
	(MessageType)(0),  // 0: protocol.MessageType
	(*EventMeta)(nil), // 1: protocol.EventMeta
	(*Message)(nil),   // 2: protocol.Message
}
var file_internal_protocol_proto_message_proto_depIdxs = []int32{
	0, // 0: protocol.Message.type:type_name -> protocol.MessageType
	1, // 1: protocol.Message.event:type_name -> protocol.EventMeta
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_protocol_proto_message_proto_init() }
func file_internal_protocol_proto_message_proto_init() {
	if File_internal_protocol_proto_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_message_proto_rawDesc), len(file_internal_protocol_proto_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_proto_message_proto_goTypes,
		DependencyIndexes: file_internal_protocol_proto_message_proto_depIdxs,
		EnumInfos:         file_internal_protocol_proto_message_proto_enumTypes,
		MessageInfos:      file_internal_protocol_proto_message_proto_msgTypes,
	}.Build()
	File_internal_protocol_proto_message_proto = out.File
	file_internal_protocol_proto_message_proto_goTypes = nil
	file_internal_protocol_proto_message_proto_depIdxs = nil
}
