// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.13.0
// source: internal/protocol/proto/server.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NegotiatedPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	ServerVersion   string                 `protobuf:"bytes,2,opt,name=server_version,json=serverVersion,proto3" json:"server_version,omitempty"`
	Capabilities    []string               `protobuf:"bytes,3,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	ClientKind      string                 `protobuf:"bytes,4,opt,name=client_kind,json=clientKind,proto3" json:"client_kind,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *NegotiatedPayload) Reset() {
	*x = NegotiatedPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NegotiatedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NegotiatedPayload) ProtoMessage() {}

func (x *NegotiatedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NegotiatedPayload.ProtoReflect.Descriptor instead.
func (*NegotiatedPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{0}
}

func (x *NegotiatedPayload) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *NegotiatedPayload) GetServerVersion() string {
	if x != nil {
		return x.ServerVersion
	}
	return ""
}

func (x *NegotiatedPayload) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *NegotiatedPayload) GetClientKind() string {
	if x != nil {
		return x.ClientKind
	}
	return ""
}

type ProtocolRejectedPayload struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	RequestId                string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Reason                   string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	SupportedProtocolVersion string                 `protobuf:"bytes,3,opt,name=supported_protocol_version,json=supportedProtocolVersion,proto3" json:"supported_protocol_version,omitempty"`
	MinClientVersion         string                 `protobuf:"bytes,4,opt,name=min_client_version,json=minClientVersion,proto3" json:"min_client_version,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ProtocolRejectedPayload) Reset() {
	*x = ProtocolRejectedPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ProtocolRejectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProtocolRejectedPayload) ProtoMessage() {}

func (x *ProtocolRejectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProtocolRejectedPayload.ProtoReflect.Descriptor instead.
func (*ProtocolRejectedPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{1}
}

func (x *ProtocolRejectedPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ProtocolRejectedPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ProtocolRejectedPayload) GetSupportedProtocolVersion() string {
	if x != nil {
		return x.SupportedProtocolVersion
	}
	return ""
}

func (x *ProtocolRejectedPayload) GetMinClientVersion() string {
	if x != nil {
		return x.MinClientVersion
	}
	return ""
}

type CommandAckPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	CommandType   MessageType            `protobuf:"varint,2,opt,name=command_type,json=commandType,proto3,enum=protocol.MessageType" json:"command_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommandAckPayload) Reset() {
	*x = CommandAckPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommandAckPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommandAckPayload) ProtoMessage() {}

func (x *CommandAckPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommandAckPayload.ProtoReflect.Descriptor instead.
func (*CommandAckPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{2}
}

func (x *CommandAckPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *CommandAckPayload) GetCommandType() MessageType {
	if x != nil {
		return x.CommandType
	}
	return MessageType_MSG_UNKNOWN
}

type WarningPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WarningPayload) Reset() {
	*x = WarningPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WarningPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WarningPayload) ProtoMessage() {}

func (x *WarningPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WarningPayload.ProtoReflect.Descriptor instead.
func (*WarningPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{3}
}

func (x *WarningPayload) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *WarningPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// ConnectedPayload 连接成功响应
type ConnectedPayload struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PlayerId           string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName         string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ReconnectToken     string                 `protobuf:"bytes,3,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	WebSessionTicket   string                 `protobuf:"bytes,4,opt,name=web_session_ticket,json=webSessionTicket,proto3" json:"web_session_ticket,omitempty"`
	ReconnectAvailable bool                   `protobuf:"varint,5,opt,name=reconnect_available,json=reconnectAvailable,proto3" json:"reconnect_available,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ConnectedPayload) Reset() {
	*x = ConnectedPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectedPayload) ProtoMessage() {}

func (x *ConnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectedPayload.ProtoReflect.Descriptor instead.
func (*ConnectedPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{4}
}

func (x *ConnectedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ConnectedPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ConnectedPayload) GetReconnectToken() string {
	if x != nil {
		return x.ReconnectToken
	}
	return ""
}

func (x *ConnectedPayload) GetWebSessionTicket() string {
	if x != nil {
		return x.WebSessionTicket
	}
	return ""
}

func (x *ConnectedPayload) GetReconnectAvailable() bool {
	if x != nil {
		return x.ReconnectAvailable
	}
	return false
}

// ReconnectedPayload 重连成功响应
type ReconnectedPayload struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PlayerId         string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName       string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	RoomCode         string                 `protobuf:"bytes,3,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	GameState        *GameStateDTO          `protobuf:"bytes,4,opt,name=game_state,json=gameState,proto3" json:"game_state,omitempty"`
	ReconnectToken   string                 `protobuf:"bytes,5,opt,name=reconnect_token,json=reconnectToken,proto3" json:"reconnect_token,omitempty"`
	WebSessionTicket string                 `protobuf:"bytes,6,opt,name=web_session_ticket,json=webSessionTicket,proto3" json:"web_session_ticket,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ReconnectedPayload) Reset() {
	*x = ReconnectedPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconnectedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconnectedPayload) ProtoMessage() {}

func (x *ReconnectedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconnectedPayload.ProtoReflect.Descriptor instead.
func (*ReconnectedPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{5}
}

func (x *ReconnectedPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ReconnectedPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *ReconnectedPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

func (x *ReconnectedPayload) GetGameState() *GameStateDTO {
	if x != nil {
		return x.GameState
	}
	return nil
}

func (x *ReconnectedPayload) GetReconnectToken() string {
	if x != nil {
		return x.ReconnectToken
	}
	return ""
}

func (x *ReconnectedPayload) GetWebSessionTicket() string {
	if x != nil {
		return x.WebSessionTicket
	}
	return ""
}

// PongPayload 心跳响应
type PongPayload struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ClientTimestamp int64                  `protobuf:"varint,1,opt,name=client_timestamp,json=clientTimestamp,proto3" json:"client_timestamp,omitempty"`
	ServerTimestamp int64                  `protobuf:"varint,2,opt,name=server_timestamp,json=serverTimestamp,proto3" json:"server_timestamp,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PongPayload) Reset() {
	*x = PongPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongPayload) ProtoMessage() {}

func (x *PongPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongPayload.ProtoReflect.Descriptor instead.
func (*PongPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{6}
}

func (x *PongPayload) GetClientTimestamp() int64 {
	if x != nil {
		return x.ClientTimestamp
	}
	return 0
}

func (x *PongPayload) GetServerTimestamp() int64 {
	if x != nil {
		return x.ServerTimestamp
	}
	return 0
}

// PlayerOfflinePayload 玩家掉线通知
type PlayerOfflinePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Timeout       int64                  `protobuf:"varint,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOfflinePayload) Reset() {
	*x = PlayerOfflinePayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOfflinePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOfflinePayload) ProtoMessage() {}

func (x *PlayerOfflinePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOfflinePayload.ProtoReflect.Descriptor instead.
func (*PlayerOfflinePayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{7}
}

func (x *PlayerOfflinePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOfflinePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *PlayerOfflinePayload) GetTimeout() int64 {
	if x != nil {
		return x.Timeout
	}
	return 0
}

// PlayerOnlinePayload 玩家上线通知
type PlayerOnlinePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayerOnlinePayload) Reset() {
	*x = PlayerOnlinePayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayerOnlinePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayerOnlinePayload) ProtoMessage() {}

func (x *PlayerOnlinePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayerOnlinePayload.ProtoReflect.Descriptor instead.
func (*PlayerOnlinePayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{8}
}

func (x *PlayerOnlinePayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *PlayerOnlinePayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

// OnlineCountPayload 在线人数更新
type OnlineCountPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         int64                  `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineCountPayload) Reset() {
	*x = OnlineCountPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineCountPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineCountPayload) ProtoMessage() {}

func (x *OnlineCountPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineCountPayload.ProtoReflect.Descriptor instead.
func (*OnlineCountPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{9}
}

func (x *OnlineCountPayload) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

// MaintenanceStatusPayload 维护状态响应
type MaintenanceStatusPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maintenance   bool                   `protobuf:"varint,1,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenanceStatusPayload) Reset() {
	*x = MaintenanceStatusPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenanceStatusPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenanceStatusPayload) ProtoMessage() {}

func (x *MaintenanceStatusPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenanceStatusPayload.ProtoReflect.Descriptor instead.
func (*MaintenanceStatusPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{10}
}

func (x *MaintenanceStatusPayload) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

// MaintenancePayload 维护模式通知
type MaintenancePayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Maintenance   bool                   `protobuf:"varint,1,opt,name=maintenance,proto3" json:"maintenance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaintenancePayload) Reset() {
	*x = MaintenancePayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaintenancePayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaintenancePayload) ProtoMessage() {}

func (x *MaintenancePayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaintenancePayload.ProtoReflect.Descriptor instead.
func (*MaintenancePayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{11}
}

func (x *MaintenancePayload) GetMaintenance() bool {
	if x != nil {
		return x.Maintenance
	}
	return false
}

// ErrorPayload 错误响应
type ErrorPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          int64                  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	CommandType   MessageType            `protobuf:"varint,3,opt,name=command_type,json=commandType,proto3,enum=protocol.MessageType" json:"command_type,omitempty"`
	RequestId     string                 `protobuf:"bytes,4,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorPayload) Reset() {
	*x = ErrorPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorPayload) ProtoMessage() {}

func (x *ErrorPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorPayload.ProtoReflect.Descriptor instead.
func (*ErrorPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorPayload) GetCode() int64 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ErrorPayload) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ErrorPayload) GetCommandType() MessageType {
	if x != nil {
		return x.CommandType
	}
	return MessageType_MSG_UNKNOWN
}

func (x *ErrorPayload) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// MatchQueuedPayload 匹配请求已由服务端接受。
type MatchQueuedPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DeadlineMs    int64                  `protobuf:"varint,1,opt,name=deadline_ms,json=deadlineMs,proto3" json:"deadline_ms,omitempty"`
	Practice      bool                   `protobuf:"varint,2,opt,name=practice,proto3" json:"practice,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchQueuedPayload) Reset() {
	*x = MatchQueuedPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchQueuedPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchQueuedPayload) ProtoMessage() {}

func (x *MatchQueuedPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchQueuedPayload.ProtoReflect.Descriptor instead.
func (*MatchQueuedPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{13}
}

func (x *MatchQueuedPayload) GetDeadlineMs() int64 {
	if x != nil {
		return x.DeadlineMs
	}
	return 0
}

func (x *MatchQueuedPayload) GetPractice() bool {
	if x != nil {
		return x.Practice
	}
	return false
}

// MatchCancelledPayload 匹配请求已由服务端取消。
type MatchCancelledPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        string                 `protobuf:"bytes,1,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchCancelledPayload) Reset() {
	*x = MatchCancelledPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchCancelledPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchCancelledPayload) ProtoMessage() {}

func (x *MatchCancelledPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchCancelledPayload.ProtoReflect.Descriptor instead.
func (*MatchCancelledPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{14}
}

func (x *MatchCancelledPayload) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// RoomLeftPayload 玩家已从服务端房间状态中移除。
type RoomLeftPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoomCode      string                 `protobuf:"bytes,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomLeftPayload) Reset() {
	*x = RoomLeftPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomLeftPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomLeftPayload) ProtoMessage() {}

func (x *RoomLeftPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomLeftPayload.ProtoReflect.Descriptor instead.
func (*RoomLeftPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{15}
}

func (x *RoomLeftPayload) GetRoomCode() string {
	if x != nil {
		return x.RoomCode
	}
	return ""
}

// StatsResultPayload 个人统计结果
type StatsResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName    string                 `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	TotalGames    int64                  `protobuf:"varint,3,opt,name=total_games,json=totalGames,proto3" json:"total_games,omitempty"`
	Wins          int64                  `protobuf:"varint,4,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses        int64                  `protobuf:"varint,5,opt,name=losses,proto3" json:"losses,omitempty"`
	WinRate       float64                `protobuf:"fixed64,6,opt,name=win_rate,json=winRate,proto3" json:"win_rate,omitempty"`
	LandlordGames int64                  `protobuf:"varint,7,opt,name=landlord_games,json=landlordGames,proto3" json:"landlord_games,omitempty"`
	LandlordWins  int64                  `protobuf:"varint,8,opt,name=landlord_wins,json=landlordWins,proto3" json:"landlord_wins,omitempty"`
	FarmerGames   int64                  `protobuf:"varint,9,opt,name=farmer_games,json=farmerGames,proto3" json:"farmer_games,omitempty"`
	FarmerWins    int64                  `protobuf:"varint,10,opt,name=farmer_wins,json=farmerWins,proto3" json:"farmer_wins,omitempty"`
	Score         int64                  `protobuf:"varint,11,opt,name=score,proto3" json:"score,omitempty"`
	Rank          int64                  `protobuf:"varint,12,opt,name=rank,proto3" json:"rank,omitempty"`
	CurrentStreak int64                  `protobuf:"varint,13,opt,name=current_streak,json=currentStreak,proto3" json:"current_streak,omitempty"`
	MaxWinStreak  int64                  `protobuf:"varint,14,opt,name=max_win_streak,json=maxWinStreak,proto3" json:"max_win_streak,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsResultPayload) Reset() {
	*x = StatsResultPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsResultPayload) ProtoMessage() {}

func (x *StatsResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsResultPayload.ProtoReflect.Descriptor instead.
func (*StatsResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{16}
}

func (x *StatsResultPayload) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *StatsResultPayload) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *StatsResultPayload) GetTotalGames() int64 {
	if x != nil {
		return x.TotalGames
	}
	return 0
}

func (x *StatsResultPayload) GetWins() int64 {
	if x != nil {
		return x.Wins
	}
	return 0
}

func (x *StatsResultPayload) GetLosses() int64 {
	if x != nil {
		return x.Losses
	}
	return 0
}

func (x *StatsResultPayload) GetWinRate() float64 {
	if x != nil {
		return x.WinRate
	}
	return 0
}

func (x *StatsResultPayload) GetLandlordGames() int64 {
	if x != nil {
		return x.LandlordGames
	}
	return 0
}

func (x *StatsResultPayload) GetLandlordWins() int64 {
	if x != nil {
		return x.LandlordWins
	}
	return 0
}

func (x *StatsResultPayload) GetFarmerGames() int64 {
	if x != nil {
		return x.FarmerGames
	}
	return 0
}

func (x *StatsResultPayload) GetFarmerWins() int64 {
	if x != nil {
		return x.FarmerWins
	}
	return 0
}

func (x *StatsResultPayload) GetScore() int64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *StatsResultPayload) GetRank() int64 {
	if x != nil {
		return x.Rank
	}
	return 0
}

func (x *StatsResultPayload) GetCurrentStreak() int64 {
	if x != nil {
		return x.CurrentStreak
	}
	return 0
}

func (x *StatsResultPayload) GetMaxWinStreak() int64 {
	if x != nil {
		return x.MaxWinStreak
	}
	return 0
}

// LeaderboardResultPayload 排行榜结果
type LeaderboardResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Entries       []*LeaderboardEntry    `protobuf:"bytes,2,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderboardResultPayload) Reset() {
	*x = LeaderboardResultPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderboardResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderboardResultPayload) ProtoMessage() {}

func (x *LeaderboardResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderboardResultPayload.ProtoReflect.Descriptor instead.
func (*LeaderboardResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{17}
}

func (x *LeaderboardResultPayload) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *LeaderboardResultPayload) GetEntries() []*LeaderboardEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

// RoomListResultPayload 房间列表结果
type RoomListResultPayload struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rooms         []*RoomListItem        `protobuf:"bytes,1,rep,name=rooms,proto3" json:"rooms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoomListResultPayload) Reset() {
	*x = RoomListResultPayload{}
	mi := &file_internal_protocol_proto_server_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoomListResultPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoomListResultPayload) ProtoMessage() {}

func (x *RoomListResultPayload) ProtoReflect() protoreflect.Message {
	mi := &file_internal_protocol_proto_server_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoomListResultPayload.ProtoReflect.Descriptor instead.
func (*RoomListResultPayload) Descriptor() ([]byte, []int) {
	return file_internal_protocol_proto_server_proto_rawDescGZIP(), []int{18}
}

func (x *RoomListResultPayload) GetRooms() []*RoomListItem {
	if x != nil {
		return x.Rooms
	}
	return nil
}

var File_internal_protocol_proto_server_proto protoreflect.FileDescriptor

const file_internal_protocol_proto_server_proto_rawDesc = "" +
	"\n" +
	"$internal/protocol/proto/server.proto\x12\bprotocol\x1a$internal/protocol/proto/common.proto\x1a%internal/protocol/proto/message.proto\"\xaa\x01\n" +
	"\x11NegotiatedPayload\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12%\n" +
	"\x0eserver_version\x18\x02 \x01(\tR\rserverVersion\x12\"\n" +
	"\fcapabilities\x18\x03 \x03(\tR\fcapabilities\x12\x1f\n" +
	"\vclient_kind\x18\x04 \x01(\tR\n" +
	"clientKind\"\xbc\x01\n" +
	"\x17ProtocolRejectedPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\x12<\n" +
	"\x1asupported_protocol_version\x18\x03 \x01(\tR\x18supportedProtocolVersion\x12,\n" +
	"\x12min_client_version\x18\x04 \x01(\tR\x10minClientVersion\"l\n" +
	"\x11CommandAckPayload\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x128\n" +
	"\fcommand_type\x18\x02 \x01(\x0e2\x15.protocol.MessageTypeR\vcommandType\">\n" +
	"\x0eWarningPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xd8\x01\n" +
	"\x10ConnectedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12'\n" +
	"\x0freconnect_token\x18\x03 \x01(\tR\x0ereconnectToken\x12,\n" +
	"\x12web_session_ticket\x18\x04 \x01(\tR\x10webSessionTicket\x12/\n" +
	"\x13reconnect_available\x18\x05 \x01(\bR\x12reconnectAvailable\"\xfd\x01\n" +
	"\x12ReconnectedPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1b\n" +
	"\troom_code\x18\x03 \x01(\tR\broomCode\x125\n" +
	"\n" +
	"game_state\x18\x04 \x01(\v2\x16.protocol.GameStateDTOR\tgameState\x12'\n" +
	"\x0freconnect_token\x18\x05 \x01(\tR\x0ereconnectToken\x12,\n" +
	"\x12web_session_ticket\x18\x06 \x01(\tR\x10webSessionTicket\"c\n" +
	"\vPongPayload\x12)\n" +
	"\x10client_timestamp\x18\x01 \x01(\x03R\x0fclientTimestamp\x12)\n" +
	"\x10server_timestamp\x18\x02 \x01(\x03R\x0fserverTimestamp\"n\n" +
	"\x14PlayerOfflinePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x18\n" +
	"\atimeout\x18\x03 \x01(\x03R\atimeout\"S\n" +
	"\x13PlayerOnlinePayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\"*\n" +
	"\x12OnlineCountPayload\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x03R\x05count\"<\n" +
	"\x18MaintenanceStatusPayload\x12 \n" +
	"\vmaintenance\x18\x01 \x01(\bR\vmaintenance\"6\n" +
	"\x12MaintenancePayload\x12 \n" +
	"\vmaintenance\x18\x01 \x01(\bR\vmaintenance\"\x95\x01\n" +
	"\fErrorPayload\x12\x12\n" +
	"\x04code\x18\x01 \x01(\x03R\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\fcommand_type\x18\x03 \x01(\x0e2\x15.protocol.MessageTypeR\vcommandType\x12\x1d\n" +
	"\n" +
	"request_id\x18\x04 \x01(\tR\trequestId\"Q\n" +
	"\x12MatchQueuedPayload\x12\x1f\n" +
	"\vdeadline_ms\x18\x01 \x01(\x03R\n" +
	"deadlineMs\x12\x1a\n" +
	"\bpractice\x18\x02 \x01(\bR\bpractice\"/\n" +
	"\x15MatchCancelledPayload\x12\x16\n" +
	"\x06reason\x18\x01 \x01(\tR\x06reason\".\n" +
	"\x0fRoomLeftPayload\x12\x1b\n" +
	"\troom_code\x18\x01 \x01(\tR\broomCode\"\xc1\x03\n" +
	"\x12StatsResultPayload\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1f\n" +
	"\vplayer_name\x18\x02 \x01(\tR\n" +
	"playerName\x12\x1f\n" +
	"\vtotal_games\x18\x03 \x01(\x03R\n" +
	"totalGames\x12\x12\n" +
	"\x04wins\x18\x04 \x01(\x03R\x04wins\x12\x16\n" +
	"\x06losses\x18\x05 \x01(\x03R\x06losses\x12\x19\n" +
	"\bwin_rate\x18\x06 \x01(\x01R\awinRate\x12%\n" +
	"\x0elandlord_games\x18\a \x01(\x03R\rlandlordGames\x12#\n" +
	"\rlandlord_wins\x18\b \x01(\x03R\flandlordWins\x12!\n" +
	"\ffarmer_games\x18\t \x01(\x03R\vfarmerGames\x12\x1f\n" +
	"\vfarmer_wins\x18\n" +
	" \x01(\x03R\n" +
	"farmerWins\x12\x14\n" +
	"\x05score\x18\v \x01(\x03R\x05score\x12\x12\n" +
	"\x04rank\x18\f \x01(\x03R\x04rank\x12%\n" +
	"\x0ecurrent_streak\x18\r \x01(\x03R\rcurrentStreak\x12$\n" +
	"\x0emax_win_streak\x18\x0e \x01(\x03R\fmaxWinStreak\"d\n" +
	"\x18LeaderboardResultPayload\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x124\n" +
	"\aentries\x18\x02 \x03(\v2\x1a.protocol.LeaderboardEntryR\aentries\"E\n" +
	"\x15RoomListResultPayload\x12,\n" +
	"\x05rooms\x18\x01 \x03(\v2\x16.protocol.RoomListItemR\x05roomsB=Z;github.com/palemoky/fight-the-landlord/internal/protocol/pbb\x06proto3"

var (
	file_internal_protocol_proto_server_proto_rawDescOnce sync.Once
	file_internal_protocol_proto_server_proto_rawDescData []byte
)

func file_internal_protocol_proto_server_proto_rawDescGZIP() []byte {
	file_internal_protocol_proto_server_proto_rawDescOnce.Do(func() {
		file_internal_protocol_proto_server_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_server_proto_rawDesc), len(file_internal_protocol_proto_server_proto_rawDesc)))
	})
	return file_internal_protocol_proto_server_proto_rawDescData
}

var file_internal_protocol_proto_server_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_internal_protocol_proto_server_proto_goTypes = []any{
	(*NegotiatedPayload)(nil),        // 0: protocol.NegotiatedPayload
	(*ProtocolRejectedPayload)(nil),  // 1: protocol.ProtocolRejectedPayload
	(*CommandAckPayload)(nil),        // 2: protocol.CommandAckPayload
	(*WarningPayload)(nil),           // 3: protocol.WarningPayload
	(*ConnectedPayload)(nil),         // 4: protocol.ConnectedPayload
	(*ReconnectedPayload)(nil),       // 5: protocol.ReconnectedPayload
	(*PongPayload)(nil),              // 6: protocol.PongPayload
	(*PlayerOfflinePayload)(nil),     // 7: protocol.PlayerOfflinePayload
	(*PlayerOnlinePayload)(nil),      // 8: protocol.PlayerOnlinePayload
	(*OnlineCountPayload)(nil),       // 9: protocol.OnlineCountPayload
	(*MaintenanceStatusPayload)(nil), // 10: protocol.MaintenanceStatusPayload
	(*MaintenancePayload)(nil),       // 11: protocol.MaintenancePayload
	(*ErrorPayload)(nil),             // 12: protocol.ErrorPayload
	(*MatchQueuedPayload)(nil),       // 13: protocol.MatchQueuedPayload
	(*MatchCancelledPayload)(nil),    // 14: protocol.MatchCancelledPayload
	(*RoomLeftPayload)(nil),          // 15: protocol.RoomLeftPayload
	(*StatsResultPayload)(nil),       // 16: protocol.StatsResultPayload
	(*LeaderboardResultPayload)(nil), // 17: protocol.LeaderboardResultPayload
	(*RoomListResultPayload)(nil),    // 18: protocol.RoomListResultPayload
	(MessageType)(0),                 // 19: protocol.MessageType
	(*GameStateDTO)(nil),             // 20: protocol.GameStateDTO
	(*LeaderboardEntry)(nil),         // 21: protocol.LeaderboardEntry
	(*RoomListItem)(nil),             // 22: protocol.RoomListItem
}
var file_internal_protocol_proto_server_proto_depIdxs = []int32{
	19, // 0: protocol.CommandAckPayload.command_type:type_name -> protocol.MessageType
	20, // 1: protocol.ReconnectedPayload.game_state:type_name -> protocol.GameStateDTO
	19, // 2: protocol.ErrorPayload.command_type:type_name -> protocol.MessageType
	21, // 3: protocol.LeaderboardResultPayload.entries:type_name -> protocol.LeaderboardEntry
	22, // 4: protocol.RoomListResultPayload.rooms:type_name -> protocol.RoomListItem
	5,  // [5:5] is the sub-list for method output_type
	5,  // [5:5] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_internal_protocol_proto_server_proto_init() }
func file_internal_protocol_proto_server_proto_init() {
	if File_internal_protocol_proto_server_proto != nil {
		return
	}
	file_internal_protocol_proto_common_proto_init()
	file_internal_protocol_proto_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_protocol_proto_server_proto_rawDesc), len(file_internal_protocol_proto_server_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_protocol_proto_server_proto_goTypes,
		DependencyIndexes: file_internal_protocol_proto_server_proto_depIdxs,
		MessageInfos:      file_internal_protocol_proto_server_proto_msgTypes,
	}.Build()
	File_internal_protocol_proto_server_proto = out.File
	file_internal_protocol_proto_server_proto_goTypes = nil
	file_internal_protocol_proto_server_proto_depIdxs = nil
}
