// Code generated by scripts/generate-protocol.mjs; DO NOT EDIT.
// Canonical schema SHA-256: 737ede2cc3ebd2ccb1971c6faea3b3c6d98536b462494316e1e30783c7a52297

import protobuf from 'protobufjs/light';

export enum MessageType {
  MSG_UNKNOWN = 0,
  MSG_RECONNECT = 1,
  MSG_PING = 2,
  MSG_CREATE_ROOM = 3,
  MSG_JOIN_ROOM = 4,
  MSG_LEAVE_ROOM = 5,
  MSG_QUICK_MATCH = 6,
  MSG_READY = 7,
  MSG_CANCEL_READY = 8,
  MSG_BID = 9,
  MSG_PLAY_CARDS = 10,
  MSG_PASS = 11,
  MSG_GET_STATS = 12,
  MSG_GET_LEADERBOARD = 13,
  MSG_GET_ROOM_LIST = 14,
  MSG_GET_ONLINE_COUNT = 15,
  MSG_CHAT = 16,
  MSG_GET_MAINTENANCE_STATUS = 17,
  MSG_CANCEL_MATCH = 18,
  MSG_HELLO = 19,
  MSG_CONNECTED = 100,
  MSG_RECONNECTED = 101,
  MSG_PONG = 102,
  MSG_PLAYER_OFFLINE = 103,
  MSG_PLAYER_ONLINE = 104,
  MSG_ONLINE_COUNT = 105,
  MSG_ROOM_CREATED = 106,
  MSG_ROOM_JOINED = 107,
  MSG_PLAYER_JOINED = 108,
  MSG_PLAYER_LEFT = 109,
  MSG_PLAYER_READY = 110,
  MSG_MATCH_FOUND = 111,
  MSG_GAME_START = 112,
  MSG_DEAL_CARDS = 113,
  MSG_BID_TURN = 114,
  MSG_BID_RESULT = 115,
  MSG_LANDLORD = 116,
  MSG_PLAY_TURN = 117,
  MSG_CARD_PLAYED = 118,
  MSG_PLAYER_PASS = 119,
  MSG_GAME_OVER = 120,
  MSG_ROUND_RESULT = 121,
  MSG_STATS_RESULT = 122,
  MSG_LEADERBOARD_RESULT = 123,
  MSG_ROOM_LIST_RESULT = 124,
  MSG_MAINTENANCE_STATUS = 125,
  MSG_MAINTENANCE = 126,
  MSG_MATCH_QUEUED = 127,
  MSG_MATCH_CANCELLED = 128,
  MSG_ROOM_LEFT = 129,
  MSG_NEGOTIATED = 130,
  MSG_PROTOCOL_REJECTED = 131,
  MSG_COMMAND_ACK = 132,
  MSG_WARNING = 133,
  MSG_ERROR = 200,
  MSG_PRACTICE_MATCH = 201,
}

export interface BidPayload {
  bid: boolean;
}

export interface BidResultPayload {
  player_id: string;
  player_name: string;
  bid: boolean;
  is_grab: boolean;
  multiplier: number;
}

export interface BidTurnPayload {
  player_id: string;
  timeout: number;
  is_grab: boolean;
  multiplier: number;
}

export interface CardInfo {
  suit: number;
  rank: number;
  color: number;
}

export interface CardPlayedPayload {
  player_id: string;
  player_name: string;
  cards: CardInfo[];
  cards_left: number;
  hand_type: string;
}

export interface ChatPayload {
  sender_id?: string;
  sender_name?: string;
  content: string;
  scope: string;
  time?: number;
  is_system?: boolean;
  message_id?: string;
  room_code?: string;
  game_id?: string;
  server_time?: number;
}

export interface CommandAckPayload {
  request_id: string;
  command_type: MessageType;
}

export interface CommandMeta {
  request_id: string;
  expected_game_id: string;
  expected_turn_id: number;
}

export interface ConnectedPayload {
  player_id: string;
  player_name: string;
  reconnect_token: string;
}

export interface DealCardsPayload {
  cards: CardInfo[];
  bottom_cards: CardInfo[];
}

export interface ErrorPayload {
  code: number;
  message: string;
  command_type?: MessageType;
  request_id?: string;
}

export interface EventMeta {
  stream_id: string;
  event_version: number;
  game_id: string;
  turn_id: number;
  server_time_ms: number;
  turn_deadline_ms: number;
}

export interface GameOverPayload {
  winner_id: string;
  winner_name: string;
  is_landlord: boolean;
  player_hands: PlayerHand[];
  multiplier: number;
  scores: PlayerScore[];
}

export interface GameSettlementDTO {
  winner_id: string;
  winner_name: string;
  winner_is_landlord: boolean;
  multiplier: number;
  scores: PlayerScore[];
  player_hands: PlayerHand[];
}

export interface GameStartPayload {
  players: PlayerInfo[];
}

export interface GameStateDTO {
  phase: string;
  players: PlayerInfo[];
  hand: CardInfo[];
  bottom_cards: CardInfo[];
  current_turn: string;
  last_played: CardInfo[];
  last_player_id: string;
  must_play: boolean;
  can_beat: boolean;
  snapshot_version?: number;
  game_id?: string;
  bottom_cards_revealed?: boolean;
  turn_id?: number;
  turn_deadline_ms?: number;
  server_time_ms?: number;
  last_player_name?: string;
  last_hand_type?: string;
  is_grab?: boolean;
  multiplier?: number;
  base_score?: number;
  played_cards?: PlayerPlayedCards[];
  settlement?: GameSettlementDTO;
}

export interface GetLeaderboardPayload {
  type: string;
  offset: number;
  limit: number;
}

export interface HelloPayload {
  protocol_version: string;
  client_version: string;
  capabilities: string[];
  client_kind: string;
}

export interface JoinRoomPayload {
  room_code: string;
}

export interface LandlordPayload {
  player_id: string;
  player_name: string;
  bottom_cards: CardInfo[];
  multiplier: number;
}

export interface LeaderboardEntry {
  rank: number;
  player_id: string;
  player_name: string;
  score: number;
  wins: number;
  win_rate: number;
}

export interface LeaderboardResultPayload {
  type: string;
  entries: LeaderboardEntry[];
}

export interface MaintenancePayload {
  maintenance: boolean;
}

export interface MaintenanceStatusPayload {
  maintenance: boolean;
}

export interface MatchCancelledPayload {
  reason: string;
}

export interface MatchQueuedPayload {
  deadline_ms: number;
  practice: boolean;
}

export interface Message {
  type: MessageType;
  payload: Uint8Array;
  event?: EventMeta;
  command?: CommandMeta;
}

export interface NegotiatedPayload {
  protocol_version: string;
  server_version: string;
  capabilities: string[];
  client_kind: string;
}

export interface OnlineCountPayload {
  count: number;
}

export interface PingPayload {
  timestamp: number;
}

export interface PlayCardsPayload {
  cards: CardInfo[];
}

export interface PlayerHand {
  player_id: string;
  player_name: string;
  cards: CardInfo[];
}

export interface PlayerInfo {
  id: string;
  name: string;
  seat: number;
  ready: boolean;
  is_landlord: boolean;
  cards_count: number;
  online: boolean;
  is_bot?: boolean;
}

export interface PlayerJoinedPayload {
  player: PlayerInfo;
}

export interface PlayerLeftPayload {
  player_id: string;
  player_name: string;
}

export interface PlayerOfflinePayload {
  player_id: string;
  player_name: string;
  timeout: number;
}

export interface PlayerOnlinePayload {
  player_id: string;
  player_name: string;
}

export interface PlayerPassPayload {
  player_id: string;
  player_name: string;
}

export interface PlayerPlayedCards {
  player_id: string;
  cards: CardInfo[];
}

export interface PlayerReadyPayload {
  player_id: string;
  ready: boolean;
}

export interface PlayerScore {
  player_id: string;
  player_name: string;
  is_landlord: boolean;
  score: number;
}

export interface PlayTurnPayload {
  player_id: string;
  timeout: number;
  must_play: boolean;
  can_beat: boolean;
}

export interface PongPayload {
  client_timestamp: number;
  server_timestamp: number;
}

export interface ProtocolRejectedPayload {
  request_id: string;
  reason: string;
  supported_protocol_version: string;
  min_client_version: string;
}

export interface ReconnectedPayload {
  player_id: string;
  player_name: string;
  room_code?: string;
  game_state?: GameStateDTO;
  reconnect_token?: string;
}

export interface ReconnectPayload {
  token: string;
  player_id: string;
}

export interface RoomCreatedPayload {
  room_code: string;
  player: PlayerInfo;
}

export interface RoomJoinedPayload {
  room_code: string;
  player: PlayerInfo;
  players: PlayerInfo[];
}

export interface RoomLeftPayload {
  room_code: string;
}

export interface RoomListItem {
  room_code: string;
  player_count: number;
  max_players: number;
}

export interface RoomListResultPayload {
  rooms: RoomListItem[];
}

export interface StatsResultPayload {
  player_id: string;
  player_name: string;
  total_games: number;
  wins: number;
  losses: number;
  win_rate: number;
  landlord_games: number;
  landlord_wins: number;
  farmer_games: number;
  farmer_wins: number;
  score: number;
  rank: number;
  current_streak: number;
  max_win_streak: number;
}

export interface WarningPayload {
  code: number;
  message: string;
}

export const MsgType = {
  Reconnect: 'reconnect',
  Ping: 'ping',
  CreateRoom: 'create_room',
  JoinRoom: 'join_room',
  LeaveRoom: 'leave_room',
  QuickMatch: 'quick_match',
  Ready: 'ready',
  CancelReady: 'cancel_ready',
  Bid: 'bid',
  PlayCards: 'play_cards',
  Pass: 'pass',
  GetStats: 'get_stats',
  GetLeaderboard: 'get_leaderboard',
  GetRoomList: 'get_room_list',
  GetOnlineCount: 'get_online_count',
  Chat: 'chat',
  GetMaintenanceStatus: 'get_maintenance_status',
  CancelMatch: 'cancel_match',
  Hello: 'hello',
  Connected: 'connected',
  Reconnected: 'reconnected',
  Pong: 'pong',
  PlayerOffline: 'player_offline',
  PlayerOnline: 'player_online',
  OnlineCount: 'online_count',
  RoomCreated: 'room_created',
  RoomJoined: 'room_joined',
  PlayerJoined: 'player_joined',
  PlayerLeft: 'player_left',
  PlayerReady: 'player_ready',
  MatchFound: 'match_found',
  GameStart: 'game_start',
  DealCards: 'deal_cards',
  BidTurn: 'bid_turn',
  BidResult: 'bid_result',
  Landlord: 'landlord',
  PlayTurn: 'play_turn',
  CardPlayed: 'card_played',
  PlayerPass: 'player_pass',
  GameOver: 'game_over',
  RoundResult: 'round_result',
  StatsResult: 'stats_result',
  LeaderboardResult: 'leaderboard_result',
  RoomListResult: 'room_list_result',
  MaintenanceStatus: 'maintenance_status',
  Maintenance: 'maintenance',
  MatchQueued: 'match_queued',
  MatchCancelled: 'match_cancelled',
  RoomLeft: 'room_left',
  Negotiated: 'negotiated',
  ProtocolRejected: 'protocol_rejected',
  CommandAck: 'command_ack',
  Warning: 'warning',
  Error: 'error',
  PracticeMatch: 'practice_match',
} as const;

export type MessageName = (typeof MsgType)[keyof typeof MsgType];
export type EmptyPayload = Record<string, never>;

export const MESSAGE_TYPE_BY_NAME: Readonly<Record<MessageName, MessageType>> = {
  reconnect: MessageType.MSG_RECONNECT,
  ping: MessageType.MSG_PING,
  create_room: MessageType.MSG_CREATE_ROOM,
  join_room: MessageType.MSG_JOIN_ROOM,
  leave_room: MessageType.MSG_LEAVE_ROOM,
  quick_match: MessageType.MSG_QUICK_MATCH,
  ready: MessageType.MSG_READY,
  cancel_ready: MessageType.MSG_CANCEL_READY,
  bid: MessageType.MSG_BID,
  play_cards: MessageType.MSG_PLAY_CARDS,
  pass: MessageType.MSG_PASS,
  get_stats: MessageType.MSG_GET_STATS,
  get_leaderboard: MessageType.MSG_GET_LEADERBOARD,
  get_room_list: MessageType.MSG_GET_ROOM_LIST,
  get_online_count: MessageType.MSG_GET_ONLINE_COUNT,
  chat: MessageType.MSG_CHAT,
  get_maintenance_status: MessageType.MSG_GET_MAINTENANCE_STATUS,
  cancel_match: MessageType.MSG_CANCEL_MATCH,
  hello: MessageType.MSG_HELLO,
  connected: MessageType.MSG_CONNECTED,
  reconnected: MessageType.MSG_RECONNECTED,
  pong: MessageType.MSG_PONG,
  player_offline: MessageType.MSG_PLAYER_OFFLINE,
  player_online: MessageType.MSG_PLAYER_ONLINE,
  online_count: MessageType.MSG_ONLINE_COUNT,
  room_created: MessageType.MSG_ROOM_CREATED,
  room_joined: MessageType.MSG_ROOM_JOINED,
  player_joined: MessageType.MSG_PLAYER_JOINED,
  player_left: MessageType.MSG_PLAYER_LEFT,
  player_ready: MessageType.MSG_PLAYER_READY,
  match_found: MessageType.MSG_MATCH_FOUND,
  game_start: MessageType.MSG_GAME_START,
  deal_cards: MessageType.MSG_DEAL_CARDS,
  bid_turn: MessageType.MSG_BID_TURN,
  bid_result: MessageType.MSG_BID_RESULT,
  landlord: MessageType.MSG_LANDLORD,
  play_turn: MessageType.MSG_PLAY_TURN,
  card_played: MessageType.MSG_CARD_PLAYED,
  player_pass: MessageType.MSG_PLAYER_PASS,
  game_over: MessageType.MSG_GAME_OVER,
  round_result: MessageType.MSG_ROUND_RESULT,
  stats_result: MessageType.MSG_STATS_RESULT,
  leaderboard_result: MessageType.MSG_LEADERBOARD_RESULT,
  room_list_result: MessageType.MSG_ROOM_LIST_RESULT,
  maintenance_status: MessageType.MSG_MAINTENANCE_STATUS,
  maintenance: MessageType.MSG_MAINTENANCE,
  match_queued: MessageType.MSG_MATCH_QUEUED,
  match_cancelled: MessageType.MSG_MATCH_CANCELLED,
  room_left: MessageType.MSG_ROOM_LEFT,
  negotiated: MessageType.MSG_NEGOTIATED,
  protocol_rejected: MessageType.MSG_PROTOCOL_REJECTED,
  command_ack: MessageType.MSG_COMMAND_ACK,
  warning: MessageType.MSG_WARNING,
  error: MessageType.MSG_ERROR,
  practice_match: MessageType.MSG_PRACTICE_MATCH,
};

export const MESSAGE_NAME_BY_TYPE: Readonly<Record<number, MessageName>> = {
  1: 'reconnect',
  2: 'ping',
  3: 'create_room',
  4: 'join_room',
  5: 'leave_room',
  6: 'quick_match',
  7: 'ready',
  8: 'cancel_ready',
  9: 'bid',
  10: 'play_cards',
  11: 'pass',
  12: 'get_stats',
  13: 'get_leaderboard',
  14: 'get_room_list',
  15: 'get_online_count',
  16: 'chat',
  17: 'get_maintenance_status',
  18: 'cancel_match',
  19: 'hello',
  100: 'connected',
  101: 'reconnected',
  102: 'pong',
  103: 'player_offline',
  104: 'player_online',
  105: 'online_count',
  106: 'room_created',
  107: 'room_joined',
  108: 'player_joined',
  109: 'player_left',
  110: 'player_ready',
  111: 'match_found',
  112: 'game_start',
  113: 'deal_cards',
  114: 'bid_turn',
  115: 'bid_result',
  116: 'landlord',
  117: 'play_turn',
  118: 'card_played',
  119: 'player_pass',
  120: 'game_over',
  121: 'round_result',
  122: 'stats_result',
  123: 'leaderboard_result',
  124: 'room_list_result',
  125: 'maintenance_status',
  126: 'maintenance',
  127: 'match_queued',
  128: 'match_cancelled',
  129: 'room_left',
  130: 'negotiated',
  131: 'protocol_rejected',
  132: 'command_ack',
  133: 'warning',
  200: 'error',
  201: 'practice_match',
};

export const PAYLOAD_TYPE_BY_NAME: Readonly<Record<MessageName, string | null>> = {
  reconnect: 'protocol.ReconnectPayload',
  ping: 'protocol.PingPayload',
  create_room: null,
  join_room: 'protocol.JoinRoomPayload',
  leave_room: null,
  quick_match: null,
  ready: null,
  cancel_ready: null,
  bid: 'protocol.BidPayload',
  play_cards: 'protocol.PlayCardsPayload',
  pass: null,
  get_stats: null,
  get_leaderboard: 'protocol.GetLeaderboardPayload',
  get_room_list: null,
  get_online_count: null,
  chat: 'protocol.ChatPayload',
  get_maintenance_status: null,
  cancel_match: null,
  hello: 'protocol.HelloPayload',
  connected: 'protocol.ConnectedPayload',
  reconnected: 'protocol.ReconnectedPayload',
  pong: 'protocol.PongPayload',
  player_offline: 'protocol.PlayerOfflinePayload',
  player_online: 'protocol.PlayerOnlinePayload',
  online_count: 'protocol.OnlineCountPayload',
  room_created: 'protocol.RoomCreatedPayload',
  room_joined: 'protocol.RoomJoinedPayload',
  player_joined: 'protocol.PlayerJoinedPayload',
  player_left: 'protocol.PlayerLeftPayload',
  player_ready: 'protocol.PlayerReadyPayload',
  match_found: null,
  game_start: 'protocol.GameStartPayload',
  deal_cards: 'protocol.DealCardsPayload',
  bid_turn: 'protocol.BidTurnPayload',
  bid_result: 'protocol.BidResultPayload',
  landlord: 'protocol.LandlordPayload',
  play_turn: 'protocol.PlayTurnPayload',
  card_played: 'protocol.CardPlayedPayload',
  player_pass: 'protocol.PlayerPassPayload',
  game_over: 'protocol.GameOverPayload',
  round_result: null,
  stats_result: 'protocol.StatsResultPayload',
  leaderboard_result: 'protocol.LeaderboardResultPayload',
  room_list_result: 'protocol.RoomListResultPayload',
  maintenance_status: 'protocol.MaintenanceStatusPayload',
  maintenance: 'protocol.MaintenancePayload',
  match_queued: 'protocol.MatchQueuedPayload',
  match_cancelled: 'protocol.MatchCancelledPayload',
  room_left: 'protocol.RoomLeftPayload',
  negotiated: 'protocol.NegotiatedPayload',
  protocol_rejected: 'protocol.ProtocolRejectedPayload',
  command_ack: 'protocol.CommandAckPayload',
  warning: 'protocol.WarningPayload',
  error: 'protocol.ErrorPayload',
  practice_match: null,
};

export interface PayloadByName {
  reconnect: ReconnectPayload;
  ping: PingPayload;
  create_room: EmptyPayload;
  join_room: JoinRoomPayload;
  leave_room: EmptyPayload;
  quick_match: EmptyPayload;
  ready: EmptyPayload;
  cancel_ready: EmptyPayload;
  bid: BidPayload;
  play_cards: PlayCardsPayload;
  pass: EmptyPayload;
  get_stats: EmptyPayload;
  get_leaderboard: GetLeaderboardPayload;
  get_room_list: EmptyPayload;
  get_online_count: EmptyPayload;
  chat: ChatPayload;
  get_maintenance_status: EmptyPayload;
  cancel_match: EmptyPayload;
  hello: HelloPayload;
  connected: ConnectedPayload;
  reconnected: ReconnectedPayload;
  pong: PongPayload;
  player_offline: PlayerOfflinePayload;
  player_online: PlayerOnlinePayload;
  online_count: OnlineCountPayload;
  room_created: RoomCreatedPayload;
  room_joined: RoomJoinedPayload;
  player_joined: PlayerJoinedPayload;
  player_left: PlayerLeftPayload;
  player_ready: PlayerReadyPayload;
  match_found: EmptyPayload;
  game_start: GameStartPayload;
  deal_cards: DealCardsPayload;
  bid_turn: BidTurnPayload;
  bid_result: BidResultPayload;
  landlord: LandlordPayload;
  play_turn: PlayTurnPayload;
  card_played: CardPlayedPayload;
  player_pass: PlayerPassPayload;
  game_over: GameOverPayload;
  round_result: EmptyPayload;
  stats_result: StatsResultPayload;
  leaderboard_result: LeaderboardResultPayload;
  room_list_result: RoomListResultPayload;
  maintenance_status: MaintenanceStatusPayload;
  maintenance: MaintenancePayload;
  match_queued: MatchQueuedPayload;
  match_cancelled: MatchCancelledPayload;
  room_left: RoomLeftPayload;
  negotiated: NegotiatedPayload;
  protocol_rejected: ProtocolRejectedPayload;
  command_ack: CommandAckPayload;
  warning: WarningPayload;
  error: ErrorPayload;
  practice_match: EmptyPayload;
}

export type ProtocolMessage<N extends MessageName = MessageName> = {
  [K in N]: { type: K; payload: PayloadByName[K]; event?: EventMeta; command?: CommandMeta }
}[N];

const schema = {
  "nested": {
    "protocol": {
      "nested": {
        "BidPayload": {
          "fields": {
            "bid": {
              "id": 1,
              "type": "bool"
            }
          }
        },
        "BidResultPayload": {
          "fields": {
            "bid": {
              "id": 3,
              "type": "bool"
            },
            "is_grab": {
              "id": 4,
              "type": "bool"
            },
            "multiplier": {
              "id": 5,
              "type": "int64"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "BidTurnPayload": {
          "fields": {
            "is_grab": {
              "id": 3,
              "type": "bool"
            },
            "multiplier": {
              "id": 4,
              "type": "int64"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "timeout": {
              "id": 2,
              "type": "int64"
            }
          }
        },
        "CardInfo": {
          "fields": {
            "color": {
              "id": 3,
              "type": "int64"
            },
            "rank": {
              "id": 2,
              "type": "int64"
            },
            "suit": {
              "id": 1,
              "type": "int64"
            }
          }
        },
        "CardPlayedPayload": {
          "fields": {
            "cards": {
              "id": 3,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "cards_left": {
              "id": 4,
              "type": "int64"
            },
            "hand_type": {
              "id": 5,
              "type": "string"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "ChatPayload": {
          "fields": {
            "content": {
              "id": 3,
              "type": "string"
            },
            "game_id": {
              "id": 9,
              "type": "string"
            },
            "is_system": {
              "id": 6,
              "type": "bool"
            },
            "message_id": {
              "id": 7,
              "type": "string"
            },
            "room_code": {
              "id": 8,
              "type": "string"
            },
            "scope": {
              "id": 4,
              "type": "string"
            },
            "sender_id": {
              "id": 1,
              "type": "string"
            },
            "sender_name": {
              "id": 2,
              "type": "string"
            },
            "server_time": {
              "id": 10,
              "type": "int64"
            },
            "time": {
              "id": 5,
              "type": "int64"
            }
          }
        },
        "CommandAckPayload": {
          "fields": {
            "command_type": {
              "id": 2,
              "type": "MessageType"
            },
            "request_id": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "CommandMeta": {
          "fields": {
            "expected_game_id": {
              "id": 2,
              "type": "string"
            },
            "expected_turn_id": {
              "id": 3,
              "type": "int64"
            },
            "request_id": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "ConnectedPayload": {
          "fields": {
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            },
            "reconnect_token": {
              "id": 3,
              "type": "string"
            }
          }
        },
        "DealCardsPayload": {
          "fields": {
            "bottom_cards": {
              "id": 2,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "cards": {
              "id": 1,
              "rule": "repeated",
              "type": "CardInfo"
            }
          }
        },
        "ErrorPayload": {
          "fields": {
            "code": {
              "id": 1,
              "type": "int64"
            },
            "command_type": {
              "id": 3,
              "type": "MessageType"
            },
            "message": {
              "id": 2,
              "type": "string"
            },
            "request_id": {
              "id": 4,
              "type": "string"
            }
          }
        },
        "EventMeta": {
          "fields": {
            "event_version": {
              "id": 2,
              "type": "int64"
            },
            "game_id": {
              "id": 3,
              "type": "string"
            },
            "server_time_ms": {
              "id": 5,
              "type": "int64"
            },
            "stream_id": {
              "id": 1,
              "type": "string"
            },
            "turn_deadline_ms": {
              "id": 6,
              "type": "int64"
            },
            "turn_id": {
              "id": 4,
              "type": "int64"
            }
          }
        },
        "GameOverPayload": {
          "fields": {
            "is_landlord": {
              "id": 3,
              "type": "bool"
            },
            "multiplier": {
              "id": 5,
              "type": "int64"
            },
            "player_hands": {
              "id": 4,
              "rule": "repeated",
              "type": "PlayerHand"
            },
            "scores": {
              "id": 6,
              "rule": "repeated",
              "type": "PlayerScore"
            },
            "winner_id": {
              "id": 1,
              "type": "string"
            },
            "winner_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "GameSettlementDTO": {
          "fields": {
            "multiplier": {
              "id": 4,
              "type": "int64"
            },
            "player_hands": {
              "id": 6,
              "rule": "repeated",
              "type": "PlayerHand"
            },
            "scores": {
              "id": 5,
              "rule": "repeated",
              "type": "PlayerScore"
            },
            "winner_id": {
              "id": 1,
              "type": "string"
            },
            "winner_is_landlord": {
              "id": 3,
              "type": "bool"
            },
            "winner_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "GameStartPayload": {
          "fields": {
            "players": {
              "id": 1,
              "rule": "repeated",
              "type": "PlayerInfo"
            }
          }
        },
        "GameStateDTO": {
          "fields": {
            "base_score": {
              "id": 20,
              "type": "int64"
            },
            "bottom_cards": {
              "id": 4,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "bottom_cards_revealed": {
              "id": 12,
              "type": "bool"
            },
            "can_beat": {
              "id": 9,
              "type": "bool"
            },
            "current_turn": {
              "id": 5,
              "type": "string"
            },
            "game_id": {
              "id": 11,
              "type": "string"
            },
            "hand": {
              "id": 3,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "is_grab": {
              "id": 18,
              "type": "bool"
            },
            "last_hand_type": {
              "id": 17,
              "type": "string"
            },
            "last_played": {
              "id": 6,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "last_player_id": {
              "id": 7,
              "type": "string"
            },
            "last_player_name": {
              "id": 16,
              "type": "string"
            },
            "multiplier": {
              "id": 19,
              "type": "int64"
            },
            "must_play": {
              "id": 8,
              "type": "bool"
            },
            "phase": {
              "id": 1,
              "type": "string"
            },
            "played_cards": {
              "id": 21,
              "rule": "repeated",
              "type": "PlayerPlayedCards"
            },
            "players": {
              "id": 2,
              "rule": "repeated",
              "type": "PlayerInfo"
            },
            "server_time_ms": {
              "id": 15,
              "type": "int64"
            },
            "settlement": {
              "id": 22,
              "options": {
                "proto3_optional": true
              },
              "type": "GameSettlementDTO"
            },
            "snapshot_version": {
              "id": 10,
              "type": "int64"
            },
            "turn_deadline_ms": {
              "id": 14,
              "type": "int64"
            },
            "turn_id": {
              "id": 13,
              "type": "int64"
            }
          },
          "oneofs": {
            "_settlement": {
              "oneof": [
                "settlement"
              ]
            }
          }
        },
        "GetLeaderboardPayload": {
          "fields": {
            "limit": {
              "id": 3,
              "type": "int64"
            },
            "offset": {
              "id": 2,
              "type": "int64"
            },
            "type": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "HelloPayload": {
          "fields": {
            "capabilities": {
              "id": 3,
              "rule": "repeated",
              "type": "string"
            },
            "client_kind": {
              "id": 4,
              "type": "string"
            },
            "client_version": {
              "id": 2,
              "type": "string"
            },
            "protocol_version": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "JoinRoomPayload": {
          "fields": {
            "room_code": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "LandlordPayload": {
          "fields": {
            "bottom_cards": {
              "id": 3,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "multiplier": {
              "id": 4,
              "type": "int64"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "LeaderboardEntry": {
          "fields": {
            "player_id": {
              "id": 2,
              "type": "string"
            },
            "player_name": {
              "id": 3,
              "type": "string"
            },
            "rank": {
              "id": 1,
              "type": "int64"
            },
            "score": {
              "id": 4,
              "type": "int64"
            },
            "win_rate": {
              "id": 6,
              "type": "double"
            },
            "wins": {
              "id": 5,
              "type": "int64"
            }
          }
        },
        "LeaderboardResultPayload": {
          "fields": {
            "entries": {
              "id": 2,
              "rule": "repeated",
              "type": "LeaderboardEntry"
            },
            "type": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "MaintenancePayload": {
          "fields": {
            "maintenance": {
              "id": 1,
              "type": "bool"
            }
          }
        },
        "MaintenanceStatusPayload": {
          "fields": {
            "maintenance": {
              "id": 1,
              "type": "bool"
            }
          }
        },
        "MatchCancelledPayload": {
          "fields": {
            "reason": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "MatchQueuedPayload": {
          "fields": {
            "deadline_ms": {
              "id": 1,
              "type": "int64"
            },
            "practice": {
              "id": 2,
              "type": "bool"
            }
          }
        },
        "Message": {
          "fields": {
            "command": {
              "id": 4,
              "type": "CommandMeta"
            },
            "event": {
              "id": 3,
              "type": "EventMeta"
            },
            "payload": {
              "id": 2,
              "type": "bytes"
            },
            "type": {
              "id": 1,
              "type": "MessageType"
            }
          }
        },
        "MessageType": {
          "values": {
            "MSG_BID": 9,
            "MSG_BID_RESULT": 115,
            "MSG_BID_TURN": 114,
            "MSG_CANCEL_MATCH": 18,
            "MSG_CANCEL_READY": 8,
            "MSG_CARD_PLAYED": 118,
            "MSG_CHAT": 16,
            "MSG_COMMAND_ACK": 132,
            "MSG_CONNECTED": 100,
            "MSG_CREATE_ROOM": 3,
            "MSG_DEAL_CARDS": 113,
            "MSG_ERROR": 200,
            "MSG_GAME_OVER": 120,
            "MSG_GAME_START": 112,
            "MSG_GET_LEADERBOARD": 13,
            "MSG_GET_MAINTENANCE_STATUS": 17,
            "MSG_GET_ONLINE_COUNT": 15,
            "MSG_GET_ROOM_LIST": 14,
            "MSG_GET_STATS": 12,
            "MSG_HELLO": 19,
            "MSG_JOIN_ROOM": 4,
            "MSG_LANDLORD": 116,
            "MSG_LEADERBOARD_RESULT": 123,
            "MSG_LEAVE_ROOM": 5,
            "MSG_MAINTENANCE": 126,
            "MSG_MAINTENANCE_STATUS": 125,
            "MSG_MATCH_CANCELLED": 128,
            "MSG_MATCH_FOUND": 111,
            "MSG_MATCH_QUEUED": 127,
            "MSG_NEGOTIATED": 130,
            "MSG_ONLINE_COUNT": 105,
            "MSG_PASS": 11,
            "MSG_PING": 2,
            "MSG_PLAY_CARDS": 10,
            "MSG_PLAY_TURN": 117,
            "MSG_PLAYER_JOINED": 108,
            "MSG_PLAYER_LEFT": 109,
            "MSG_PLAYER_OFFLINE": 103,
            "MSG_PLAYER_ONLINE": 104,
            "MSG_PLAYER_PASS": 119,
            "MSG_PLAYER_READY": 110,
            "MSG_PONG": 102,
            "MSG_PRACTICE_MATCH": 201,
            "MSG_PROTOCOL_REJECTED": 131,
            "MSG_QUICK_MATCH": 6,
            "MSG_READY": 7,
            "MSG_RECONNECT": 1,
            "MSG_RECONNECTED": 101,
            "MSG_ROOM_CREATED": 106,
            "MSG_ROOM_JOINED": 107,
            "MSG_ROOM_LEFT": 129,
            "MSG_ROOM_LIST_RESULT": 124,
            "MSG_ROUND_RESULT": 121,
            "MSG_STATS_RESULT": 122,
            "MSG_UNKNOWN": 0,
            "MSG_WARNING": 133
          }
        },
        "NegotiatedPayload": {
          "fields": {
            "capabilities": {
              "id": 3,
              "rule": "repeated",
              "type": "string"
            },
            "client_kind": {
              "id": 4,
              "type": "string"
            },
            "protocol_version": {
              "id": 1,
              "type": "string"
            },
            "server_version": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "OnlineCountPayload": {
          "fields": {
            "count": {
              "id": 1,
              "type": "int64"
            }
          }
        },
        "PingPayload": {
          "fields": {
            "timestamp": {
              "id": 1,
              "type": "int64"
            }
          }
        },
        "PlayCardsPayload": {
          "fields": {
            "cards": {
              "id": 1,
              "rule": "repeated",
              "type": "CardInfo"
            }
          }
        },
        "PlayerHand": {
          "fields": {
            "cards": {
              "id": 3,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "PlayerInfo": {
          "fields": {
            "cards_count": {
              "id": 6,
              "type": "int64"
            },
            "id": {
              "id": 1,
              "type": "string"
            },
            "is_bot": {
              "id": 8,
              "type": "bool"
            },
            "is_landlord": {
              "id": 5,
              "type": "bool"
            },
            "name": {
              "id": 2,
              "type": "string"
            },
            "online": {
              "id": 7,
              "type": "bool"
            },
            "ready": {
              "id": 4,
              "type": "bool"
            },
            "seat": {
              "id": 3,
              "type": "int64"
            }
          }
        },
        "PlayerJoinedPayload": {
          "fields": {
            "player": {
              "id": 1,
              "type": "PlayerInfo"
            }
          }
        },
        "PlayerLeftPayload": {
          "fields": {
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "PlayerOfflinePayload": {
          "fields": {
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            },
            "timeout": {
              "id": 3,
              "type": "int64"
            }
          }
        },
        "PlayerOnlinePayload": {
          "fields": {
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "PlayerPassPayload": {
          "fields": {
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            }
          }
        },
        "PlayerPlayedCards": {
          "fields": {
            "cards": {
              "id": 2,
              "rule": "repeated",
              "type": "CardInfo"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "PlayerReadyPayload": {
          "fields": {
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "ready": {
              "id": 2,
              "type": "bool"
            }
          }
        },
        "PlayerScore": {
          "fields": {
            "is_landlord": {
              "id": 3,
              "type": "bool"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            },
            "score": {
              "id": 4,
              "type": "int64"
            }
          }
        },
        "PlayTurnPayload": {
          "fields": {
            "can_beat": {
              "id": 4,
              "type": "bool"
            },
            "must_play": {
              "id": 3,
              "type": "bool"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "timeout": {
              "id": 2,
              "type": "int64"
            }
          }
        },
        "PongPayload": {
          "fields": {
            "client_timestamp": {
              "id": 1,
              "type": "int64"
            },
            "server_timestamp": {
              "id": 2,
              "type": "int64"
            }
          }
        },
        "ProtocolRejectedPayload": {
          "fields": {
            "min_client_version": {
              "id": 4,
              "type": "string"
            },
            "reason": {
              "id": 2,
              "type": "string"
            },
            "request_id": {
              "id": 1,
              "type": "string"
            },
            "supported_protocol_version": {
              "id": 3,
              "type": "string"
            }
          }
        },
        "ReconnectedPayload": {
          "fields": {
            "game_state": {
              "id": 4,
              "type": "GameStateDTO"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            },
            "reconnect_token": {
              "id": 5,
              "type": "string"
            },
            "room_code": {
              "id": 3,
              "type": "string"
            }
          }
        },
        "ReconnectPayload": {
          "fields": {
            "player_id": {
              "id": 2,
              "type": "string"
            },
            "token": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "RoomCreatedPayload": {
          "fields": {
            "player": {
              "id": 2,
              "type": "PlayerInfo"
            },
            "room_code": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "RoomJoinedPayload": {
          "fields": {
            "player": {
              "id": 2,
              "type": "PlayerInfo"
            },
            "players": {
              "id": 3,
              "rule": "repeated",
              "type": "PlayerInfo"
            },
            "room_code": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "RoomLeftPayload": {
          "fields": {
            "room_code": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "RoomListItem": {
          "fields": {
            "max_players": {
              "id": 3,
              "type": "int64"
            },
            "player_count": {
              "id": 2,
              "type": "int64"
            },
            "room_code": {
              "id": 1,
              "type": "string"
            }
          }
        },
        "RoomListResultPayload": {
          "fields": {
            "rooms": {
              "id": 1,
              "rule": "repeated",
              "type": "RoomListItem"
            }
          }
        },
        "StatsResultPayload": {
          "fields": {
            "current_streak": {
              "id": 13,
              "type": "int64"
            },
            "farmer_games": {
              "id": 9,
              "type": "int64"
            },
            "farmer_wins": {
              "id": 10,
              "type": "int64"
            },
            "landlord_games": {
              "id": 7,
              "type": "int64"
            },
            "landlord_wins": {
              "id": 8,
              "type": "int64"
            },
            "losses": {
              "id": 5,
              "type": "int64"
            },
            "max_win_streak": {
              "id": 14,
              "type": "int64"
            },
            "player_id": {
              "id": 1,
              "type": "string"
            },
            "player_name": {
              "id": 2,
              "type": "string"
            },
            "rank": {
              "id": 12,
              "type": "int64"
            },
            "score": {
              "id": 11,
              "type": "int64"
            },
            "total_games": {
              "id": 3,
              "type": "int64"
            },
            "win_rate": {
              "id": 6,
              "type": "double"
            },
            "wins": {
              "id": 4,
              "type": "int64"
            }
          }
        },
        "WarningPayload": {
          "fields": {
            "code": {
              "id": 1,
              "type": "int64"
            },
            "message": {
              "id": 2,
              "type": "string"
            }
          }
        }
      },
      "options": {
        "go_package": "github.com/palemoky/fight-the-landlord/internal/protocol/pb"
      }
    }
  }
} satisfies protobuf.INamespace;

export const protocolRoot = protobuf.Root.fromJSON(schema);
