// Code generated by scripts/generate-protocol.mjs; DO NOT EDIT.
// Canonical schema SHA-256: 737ede2cc3ebd2ccb1971c6faea3b3c6d98536b462494316e1e30783c7a52297

export enum MessageType {
  MSG_UNKNOWN = 0,
  MSG_RECONNECT = 1,
  MSG_PING = 2,
  MSG_CREATE_ROOM = 3,
  MSG_JOIN_ROOM = 4,
  MSG_LEAVE_ROOM = 5,
  MSG_QUICK_MATCH = 6,
  MSG_READY = 7,
  MSG_CANCEL_READY = 8,
  MSG_BID = 9,
  MSG_PLAY_CARDS = 10,
  MSG_PASS = 11,
  MSG_GET_STATS = 12,
  MSG_GET_LEADERBOARD = 13,
  MSG_GET_ROOM_LIST = 14,
  MSG_GET_ONLINE_COUNT = 15,
  MSG_CHAT = 16,
  MSG_GET_MAINTENANCE_STATUS = 17,
  MSG_CANCEL_MATCH = 18,
  MSG_HELLO = 19,
  MSG_CONNECTED = 100,
  MSG_RECONNECTED = 101,
  MSG_PONG = 102,
  MSG_PLAYER_OFFLINE = 103,
  MSG_PLAYER_ONLINE = 104,
  MSG_ONLINE_COUNT = 105,
  MSG_ROOM_CREATED = 106,
  MSG_ROOM_JOINED = 107,
  MSG_PLAYER_JOINED = 108,
  MSG_PLAYER_LEFT = 109,
  MSG_PLAYER_READY = 110,
  MSG_MATCH_FOUND = 111,
  MSG_GAME_START = 112,
  MSG_DEAL_CARDS = 113,
  MSG_BID_TURN = 114,
  MSG_BID_RESULT = 115,
  MSG_LANDLORD = 116,
  MSG_PLAY_TURN = 117,
  MSG_CARD_PLAYED = 118,
  MSG_PLAYER_PASS = 119,
  MSG_GAME_OVER = 120,
  MSG_ROUND_RESULT = 121,
  MSG_STATS_RESULT = 122,
  MSG_LEADERBOARD_RESULT = 123,
  MSG_ROOM_LIST_RESULT = 124,
  MSG_MAINTENANCE_STATUS = 125,
  MSG_MAINTENANCE = 126,
  MSG_MATCH_QUEUED = 127,
  MSG_MATCH_CANCELLED = 128,
  MSG_ROOM_LEFT = 129,
  MSG_NEGOTIATED = 130,
  MSG_PROTOCOL_REJECTED = 131,
  MSG_COMMAND_ACK = 132,
  MSG_WARNING = 133,
  MSG_ERROR = 200,
  MSG_PRACTICE_MATCH = 201,
}

export interface BidPayload {
  bid: boolean;
}

export interface BidResultPayload {
  player_id: string;
  player_name: string;
  bid: boolean;
  is_grab: boolean;
  multiplier: number;
}

export interface BidTurnPayload {
  player_id: string;
  timeout: number;
  is_grab: boolean;
  multiplier: number;
}

export interface CardInfo {
  suit: number;
  rank: number;
  color: number;
}

export interface CardPlayedPayload {
  player_id: string;
  player_name: string;
  cards: CardInfo[];
  cards_left: number;
  hand_type: string;
}

export interface ChatPayload {
  sender_id?: string;
  sender_name?: string;
  content: string;
  scope: string;
  time?: number;
  is_system?: boolean;
  message_id?: string;
  room_code?: string;
  game_id?: string;
  server_time?: number;
}

export interface CommandAckPayload {
  request_id: string;
  command_type: MessageType;
}

export interface CommandMeta {
  request_id: string;
  expected_game_id: string;
  expected_turn_id: number;
}

export interface ConnectedPayload {
  player_id: string;
  player_name: string;
  reconnect_token: string;
}

export interface DealCardsPayload {
  cards: CardInfo[];
  bottom_cards: CardInfo[];
}

export interface ErrorPayload {
  code: number;
  message: string;
  command_type?: MessageType;
  request_id?: string;
}

export interface EventMeta {
  stream_id: string;
  event_version: number;
  game_id: string;
  turn_id: number;
  server_time_ms: number;
  turn_deadline_ms: number;
}

export interface GameOverPayload {
  winner_id: string;
  winner_name: string;
  is_landlord: boolean;
  player_hands: PlayerHand[];
  multiplier: number;
  scores: PlayerScore[];
}

export interface GameSettlementDTO {
  winner_id: string;
  winner_name: string;
  winner_is_landlord: boolean;
  multiplier: number;
  scores: PlayerScore[];
  player_hands: PlayerHand[];
}

export interface GameStartPayload {
  players: PlayerInfo[];
}

export interface GameStateDTO {
  phase: string;
  players: PlayerInfo[];
  hand: CardInfo[];
  bottom_cards: CardInfo[];
  current_turn: string;
  last_played: CardInfo[];
  last_player_id: string;
  must_play: boolean;
  can_beat: boolean;
  snapshot_version?: number;
  game_id?: string;
  bottom_cards_revealed?: boolean;
  turn_id?: number;
  turn_deadline_ms?: number;
  server_time_ms?: number;
  last_player_name?: string;
  last_hand_type?: string;
  is_grab?: boolean;
  multiplier?: number;
  base_score?: number;
  played_cards?: PlayerPlayedCards[];
  settlement?: GameSettlementDTO;
}

export interface GetLeaderboardPayload {
  type: string;
  offset: number;
  limit: number;
}

export interface HelloPayload {
  protocol_version: string;
  client_version: string;
  capabilities: string[];
  client_kind: string;
}

export interface JoinRoomPayload {
  room_code: string;
}

export interface LandlordPayload {
  player_id: string;
  player_name: string;
  bottom_cards: CardInfo[];
  multiplier: number;
}

export interface LeaderboardEntry {
  rank: number;
  player_id: string;
  player_name: string;
  score: number;
  wins: number;
  win_rate: number;
}

export interface LeaderboardResultPayload {
  type: string;
  entries: LeaderboardEntry[];
}

export interface MaintenancePayload {
  maintenance: boolean;
}

export interface MaintenanceStatusPayload {
  maintenance: boolean;
}

export interface MatchCancelledPayload {
  reason: string;
}

export interface MatchQueuedPayload {
  deadline_ms: number;
  practice: boolean;
}

export interface Message {
  type: MessageType;
  payload: Uint8Array;
  event?: EventMeta;
  command?: CommandMeta;
}

export interface NegotiatedPayload {
  protocol_version: string;
  server_version: string;
  capabilities: string[];
  client_kind: string;
}

export interface OnlineCountPayload {
  count: number;
}

export interface PingPayload {
  timestamp: number;
}

export interface PlayCardsPayload {
  cards: CardInfo[];
}

export interface PlayerHand {
  player_id: string;
  player_name: string;
  cards: CardInfo[];
}

export interface PlayerInfo {
  id: string;
  name: string;
  seat: number;
  ready: boolean;
  is_landlord: boolean;
  cards_count: number;
  online: boolean;
  is_bot?: boolean;
}

export interface PlayerJoinedPayload {
  player: PlayerInfo;
}

export interface PlayerLeftPayload {
  player_id: string;
  player_name: string;
}

export interface PlayerOfflinePayload {
  player_id: string;
  player_name: string;
  timeout: number;
}

export interface PlayerOnlinePayload {
  player_id: string;
  player_name: string;
}

export interface PlayerPassPayload {
  player_id: string;
  player_name: string;
}

export interface PlayerPlayedCards {
  player_id: string;
  cards: CardInfo[];
}

export interface PlayerReadyPayload {
  player_id: string;
  ready: boolean;
}

export interface PlayerScore {
  player_id: string;
  player_name: string;
  is_landlord: boolean;
  score: number;
}

export interface PlayTurnPayload {
  player_id: string;
  timeout: number;
  must_play: boolean;
  can_beat: boolean;
}

export interface PongPayload {
  client_timestamp: number;
  server_timestamp: number;
}

export interface ProtocolRejectedPayload {
  request_id: string;
  reason: string;
  supported_protocol_version: string;
  min_client_version?: string;
}

export interface ReconnectedPayload {
  player_id: string;
  player_name: string;
  room_code?: string;
  game_state?: GameStateDTO;
  reconnect_token?: string;
}

export interface ReconnectPayload {
  token: string;
  player_id: string;
}

export interface RoomCreatedPayload {
  room_code: string;
  player: PlayerInfo;
}

export interface RoomJoinedPayload {
  room_code: string;
  player: PlayerInfo;
  players: PlayerInfo[];
}

export interface RoomLeftPayload {
  room_code: string;
}

export interface RoomListItem {
  room_code: string;
  player_count: number;
  max_players: number;
}

export interface RoomListResultPayload {
  rooms: RoomListItem[];
}

export interface StatsResultPayload {
  player_id: string;
  player_name: string;
  total_games: number;
  wins: number;
  losses: number;
  win_rate: number;
  landlord_games: number;
  landlord_wins: number;
  farmer_games: number;
  farmer_wins: number;
  score: number;
  rank: number;
  current_streak: number;
  max_win_streak: number;
}

export interface WarningPayload {
  code: number;
  message: string;
}

export const MsgType = {
  Reconnect: 'reconnect',
  Ping: 'ping',
  CreateRoom: 'create_room',
  JoinRoom: 'join_room',
  LeaveRoom: 'leave_room',
  QuickMatch: 'quick_match',
  Ready: 'ready',
  CancelReady: 'cancel_ready',
  Bid: 'bid',
  PlayCards: 'play_cards',
  Pass: 'pass',
  GetStats: 'get_stats',
  GetLeaderboard: 'get_leaderboard',
  GetRoomList: 'get_room_list',
  GetOnlineCount: 'get_online_count',
  Chat: 'chat',
  GetMaintenanceStatus: 'get_maintenance_status',
  CancelMatch: 'cancel_match',
  Hello: 'hello',
  Connected: 'connected',
  Reconnected: 'reconnected',
  Pong: 'pong',
  PlayerOffline: 'player_offline',
  PlayerOnline: 'player_online',
  OnlineCount: 'online_count',
  RoomCreated: 'room_created',
  RoomJoined: 'room_joined',
  PlayerJoined: 'player_joined',
  PlayerLeft: 'player_left',
  PlayerReady: 'player_ready',
  MatchFound: 'match_found',
  GameStart: 'game_start',
  DealCards: 'deal_cards',
  BidTurn: 'bid_turn',
  BidResult: 'bid_result',
  Landlord: 'landlord',
  PlayTurn: 'play_turn',
  CardPlayed: 'card_played',
  PlayerPass: 'player_pass',
  GameOver: 'game_over',
  RoundResult: 'round_result',
  StatsResult: 'stats_result',
  LeaderboardResult: 'leaderboard_result',
  RoomListResult: 'room_list_result',
  MaintenanceStatus: 'maintenance_status',
  Maintenance: 'maintenance',
  MatchQueued: 'match_queued',
  MatchCancelled: 'match_cancelled',
  RoomLeft: 'room_left',
  Negotiated: 'negotiated',
  ProtocolRejected: 'protocol_rejected',
  CommandAck: 'command_ack',
  Warning: 'warning',
  Error: 'error',
  PracticeMatch: 'practice_match',
} as const;

export type MessageName = (typeof MsgType)[keyof typeof MsgType];
export type EmptyPayload = Record<string, never>;

export const MESSAGE_TYPE_BY_NAME: Readonly<Record<MessageName, MessageType>> = {
  reconnect: MessageType.MSG_RECONNECT,
  ping: MessageType.MSG_PING,
  create_room: MessageType.MSG_CREATE_ROOM,
  join_room: MessageType.MSG_JOIN_ROOM,
  leave_room: MessageType.MSG_LEAVE_ROOM,
  quick_match: MessageType.MSG_QUICK_MATCH,
  ready: MessageType.MSG_READY,
  cancel_ready: MessageType.MSG_CANCEL_READY,
  bid: MessageType.MSG_BID,
  play_cards: MessageType.MSG_PLAY_CARDS,
  pass: MessageType.MSG_PASS,
  get_stats: MessageType.MSG_GET_STATS,
  get_leaderboard: MessageType.MSG_GET_LEADERBOARD,
  get_room_list: MessageType.MSG_GET_ROOM_LIST,
  get_online_count: MessageType.MSG_GET_ONLINE_COUNT,
  chat: MessageType.MSG_CHAT,
  get_maintenance_status: MessageType.MSG_GET_MAINTENANCE_STATUS,
  cancel_match: MessageType.MSG_CANCEL_MATCH,
  hello: MessageType.MSG_HELLO,
  connected: MessageType.MSG_CONNECTED,
  reconnected: MessageType.MSG_RECONNECTED,
  pong: MessageType.MSG_PONG,
  player_offline: MessageType.MSG_PLAYER_OFFLINE,
  player_online: MessageType.MSG_PLAYER_ONLINE,
  online_count: MessageType.MSG_ONLINE_COUNT,
  room_created: MessageType.MSG_ROOM_CREATED,
  room_joined: MessageType.MSG_ROOM_JOINED,
  player_joined: MessageType.MSG_PLAYER_JOINED,
  player_left: MessageType.MSG_PLAYER_LEFT,
  player_ready: MessageType.MSG_PLAYER_READY,
  match_found: MessageType.MSG_MATCH_FOUND,
  game_start: MessageType.MSG_GAME_START,
  deal_cards: MessageType.MSG_DEAL_CARDS,
  bid_turn: MessageType.MSG_BID_TURN,
  bid_result: MessageType.MSG_BID_RESULT,
  landlord: MessageType.MSG_LANDLORD,
  play_turn: MessageType.MSG_PLAY_TURN,
  card_played: MessageType.MSG_CARD_PLAYED,
  player_pass: MessageType.MSG_PLAYER_PASS,
  game_over: MessageType.MSG_GAME_OVER,
  round_result: MessageType.MSG_ROUND_RESULT,
  stats_result: MessageType.MSG_STATS_RESULT,
  leaderboard_result: MessageType.MSG_LEADERBOARD_RESULT,
  room_list_result: MessageType.MSG_ROOM_LIST_RESULT,
  maintenance_status: MessageType.MSG_MAINTENANCE_STATUS,
  maintenance: MessageType.MSG_MAINTENANCE,
  match_queued: MessageType.MSG_MATCH_QUEUED,
  match_cancelled: MessageType.MSG_MATCH_CANCELLED,
  room_left: MessageType.MSG_ROOM_LEFT,
  negotiated: MessageType.MSG_NEGOTIATED,
  protocol_rejected: MessageType.MSG_PROTOCOL_REJECTED,
  command_ack: MessageType.MSG_COMMAND_ACK,
  warning: MessageType.MSG_WARNING,
  error: MessageType.MSG_ERROR,
  practice_match: MessageType.MSG_PRACTICE_MATCH,
};

export const MESSAGE_NAME_BY_TYPE: Readonly<Record<number, MessageName>> = {
  1: 'reconnect',
  2: 'ping',
  3: 'create_room',
  4: 'join_room',
  5: 'leave_room',
  6: 'quick_match',
  7: 'ready',
  8: 'cancel_ready',
  9: 'bid',
  10: 'play_cards',
  11: 'pass',
  12: 'get_stats',
  13: 'get_leaderboard',
  14: 'get_room_list',
  15: 'get_online_count',
  16: 'chat',
  17: 'get_maintenance_status',
  18: 'cancel_match',
  19: 'hello',
  100: 'connected',
  101: 'reconnected',
  102: 'pong',
  103: 'player_offline',
  104: 'player_online',
  105: 'online_count',
  106: 'room_created',
  107: 'room_joined',
  108: 'player_joined',
  109: 'player_left',
  110: 'player_ready',
  111: 'match_found',
  112: 'game_start',
  113: 'deal_cards',
  114: 'bid_turn',
  115: 'bid_result',
  116: 'landlord',
  117: 'play_turn',
  118: 'card_played',
  119: 'player_pass',
  120: 'game_over',
  121: 'round_result',
  122: 'stats_result',
  123: 'leaderboard_result',
  124: 'room_list_result',
  125: 'maintenance_status',
  126: 'maintenance',
  127: 'match_queued',
  128: 'match_cancelled',
  129: 'room_left',
  130: 'negotiated',
  131: 'protocol_rejected',
  132: 'command_ack',
  133: 'warning',
  200: 'error',
  201: 'practice_match',
};

export const PAYLOAD_TYPE_BY_NAME: Readonly<Record<MessageName, string | null>> = {
  reconnect: 'protocol.ReconnectPayload',
  ping: 'protocol.PingPayload',
  create_room: null,
  join_room: 'protocol.JoinRoomPayload',
  leave_room: null,
  quick_match: null,
  ready: null,
  cancel_ready: null,
  bid: 'protocol.BidPayload',
  play_cards: 'protocol.PlayCardsPayload',
  pass: null,
  get_stats: null,
  get_leaderboard: 'protocol.GetLeaderboardPayload',
  get_room_list: null,
  get_online_count: null,
  chat: 'protocol.ChatPayload',
  get_maintenance_status: null,
  cancel_match: null,
  hello: 'protocol.HelloPayload',
  connected: 'protocol.ConnectedPayload',
  reconnected: 'protocol.ReconnectedPayload',
  pong: 'protocol.PongPayload',
  player_offline: 'protocol.PlayerOfflinePayload',
  player_online: 'protocol.PlayerOnlinePayload',
  online_count: 'protocol.OnlineCountPayload',
  room_created: 'protocol.RoomCreatedPayload',
  room_joined: 'protocol.RoomJoinedPayload',
  player_joined: 'protocol.PlayerJoinedPayload',
  player_left: 'protocol.PlayerLeftPayload',
  player_ready: 'protocol.PlayerReadyPayload',
  match_found: null,
  game_start: 'protocol.GameStartPayload',
  deal_cards: 'protocol.DealCardsPayload',
  bid_turn: 'protocol.BidTurnPayload',
  bid_result: 'protocol.BidResultPayload',
  landlord: 'protocol.LandlordPayload',
  play_turn: 'protocol.PlayTurnPayload',
  card_played: 'protocol.CardPlayedPayload',
  player_pass: 'protocol.PlayerPassPayload',
  game_over: 'protocol.GameOverPayload',
  round_result: null,
  stats_result: 'protocol.StatsResultPayload',
  leaderboard_result: 'protocol.LeaderboardResultPayload',
  room_list_result: 'protocol.RoomListResultPayload',
  maintenance_status: 'protocol.MaintenanceStatusPayload',
  maintenance: 'protocol.MaintenancePayload',
  match_queued: 'protocol.MatchQueuedPayload',
  match_cancelled: 'protocol.MatchCancelledPayload',
  room_left: 'protocol.RoomLeftPayload',
  negotiated: 'protocol.NegotiatedPayload',
  protocol_rejected: 'protocol.ProtocolRejectedPayload',
  command_ack: 'protocol.CommandAckPayload',
  warning: 'protocol.WarningPayload',
  error: 'protocol.ErrorPayload',
  practice_match: null,
};

export const REQUIRED_FIELDS_BY_NAME: Readonly<Partial<Record<MessageName, readonly string[]>>> = {
  reconnect: ['token', 'player_id'],
  ping: ['timestamp'],
  join_room: ['room_code'],
  bid: ['bid'],
  play_cards: ['cards'],
  get_leaderboard: ['type', 'offset', 'limit'],
  chat: ['content', 'scope'],
  hello: ['protocol_version', 'client_version', 'capabilities', 'client_kind'],
  connected: ['player_id', 'player_name', 'reconnect_token'],
  reconnected: ['player_id', 'player_name'],
  pong: ['client_timestamp', 'server_timestamp'],
  player_offline: ['player_id', 'player_name', 'timeout'],
  player_online: ['player_id', 'player_name'],
  online_count: ['count'],
  room_created: ['room_code', 'player'],
  room_joined: ['room_code', 'player', 'players'],
  player_joined: ['player'],
  player_left: ['player_id', 'player_name'],
  player_ready: ['player_id', 'ready'],
  game_start: ['players'],
  deal_cards: ['cards', 'bottom_cards'],
  bid_turn: ['player_id', 'timeout', 'is_grab', 'multiplier'],
  bid_result: ['player_id', 'player_name', 'bid', 'is_grab', 'multiplier'],
  landlord: ['player_id', 'player_name', 'bottom_cards', 'multiplier'],
  play_turn: ['player_id', 'timeout', 'must_play', 'can_beat'],
  card_played: ['player_id', 'player_name', 'cards', 'cards_left', 'hand_type'],
  player_pass: ['player_id', 'player_name'],
  game_over: ['winner_id', 'winner_name', 'is_landlord', 'player_hands', 'multiplier', 'scores'],
  stats_result: ['player_id', 'player_name', 'total_games', 'wins', 'losses', 'win_rate', 'landlord_games', 'landlord_wins', 'farmer_games', 'farmer_wins', 'score', 'rank', 'current_streak', 'max_win_streak'],
  leaderboard_result: ['type', 'entries'],
  room_list_result: ['rooms'],
  maintenance_status: ['maintenance'],
  maintenance: ['maintenance'],
  match_queued: ['deadline_ms', 'practice'],
  match_cancelled: ['reason'],
  room_left: ['room_code'],
  negotiated: ['protocol_version', 'server_version', 'capabilities', 'client_kind'],
  protocol_rejected: ['request_id', 'reason', 'supported_protocol_version'],
  command_ack: ['request_id', 'command_type'],
  warning: ['code', 'message'],
  error: ['code', 'message'],
};

export interface PayloadByName {
  reconnect: ReconnectPayload;
  ping: PingPayload;
  create_room: EmptyPayload;
  join_room: JoinRoomPayload;
  leave_room: EmptyPayload;
  quick_match: EmptyPayload;
  ready: EmptyPayload;
  cancel_ready: EmptyPayload;
  bid: BidPayload;
  play_cards: PlayCardsPayload;
  pass: EmptyPayload;
  get_stats: EmptyPayload;
  get_leaderboard: GetLeaderboardPayload;
  get_room_list: EmptyPayload;
  get_online_count: EmptyPayload;
  chat: ChatPayload;
  get_maintenance_status: EmptyPayload;
  cancel_match: EmptyPayload;
  hello: HelloPayload;
  connected: ConnectedPayload;
  reconnected: ReconnectedPayload;
  pong: PongPayload;
  player_offline: PlayerOfflinePayload;
  player_online: PlayerOnlinePayload;
  online_count: OnlineCountPayload;
  room_created: RoomCreatedPayload;
  room_joined: RoomJoinedPayload;
  player_joined: PlayerJoinedPayload;
  player_left: PlayerLeftPayload;
  player_ready: PlayerReadyPayload;
  match_found: EmptyPayload;
  game_start: GameStartPayload;
  deal_cards: DealCardsPayload;
  bid_turn: BidTurnPayload;
  bid_result: BidResultPayload;
  landlord: LandlordPayload;
  play_turn: PlayTurnPayload;
  card_played: CardPlayedPayload;
  player_pass: PlayerPassPayload;
  game_over: GameOverPayload;
  round_result: EmptyPayload;
  stats_result: StatsResultPayload;
  leaderboard_result: LeaderboardResultPayload;
  room_list_result: RoomListResultPayload;
  maintenance_status: MaintenanceStatusPayload;
  maintenance: MaintenancePayload;
  match_queued: MatchQueuedPayload;
  match_cancelled: MatchCancelledPayload;
  room_left: RoomLeftPayload;
  negotiated: NegotiatedPayload;
  protocol_rejected: ProtocolRejectedPayload;
  command_ack: CommandAckPayload;
  warning: WarningPayload;
  error: ErrorPayload;
  practice_match: EmptyPayload;
}

export type ProtocolMessage<N extends MessageName = MessageName> = {
  [K in N]: { type: K; payload: PayloadByName[K]; event?: EventMeta; command?: CommandMeta }
}[N];

export type Int64FieldMetadata =
  | { readonly name: string; readonly repeated: boolean; readonly kind: 'int64' }
  | { readonly name: string; readonly repeated: boolean; readonly kind: 'message'; readonly message_type: string };

export const INT64_FIELD_METADATA_BY_TYPE: Readonly<Record<string, readonly Int64FieldMetadata[]>> = {
  'protocol.BidResultPayload': [
    { name: 'multiplier', repeated: false, kind: 'int64' },
  ],
  'protocol.BidTurnPayload': [
    { name: 'timeout', repeated: false, kind: 'int64' },
    { name: 'multiplier', repeated: false, kind: 'int64' },
  ],
  'protocol.CardInfo': [
    { name: 'suit', repeated: false, kind: 'int64' },
    { name: 'rank', repeated: false, kind: 'int64' },
    { name: 'color', repeated: false, kind: 'int64' },
  ],
  'protocol.CardPlayedPayload': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'cards_left', repeated: false, kind: 'int64' },
  ],
  'protocol.ChatPayload': [
    { name: 'time', repeated: false, kind: 'int64' },
    { name: 'server_time', repeated: false, kind: 'int64' },
  ],
  'protocol.CommandMeta': [
    { name: 'expected_turn_id', repeated: false, kind: 'int64' },
  ],
  'protocol.DealCardsPayload': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'bottom_cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.ErrorPayload': [
    { name: 'code', repeated: false, kind: 'int64' },
  ],
  'protocol.EventMeta': [
    { name: 'event_version', repeated: false, kind: 'int64' },
    { name: 'turn_id', repeated: false, kind: 'int64' },
    { name: 'server_time_ms', repeated: false, kind: 'int64' },
    { name: 'turn_deadline_ms', repeated: false, kind: 'int64' },
  ],
  'protocol.GameOverPayload': [
    { name: 'player_hands', repeated: true, kind: 'message', message_type: 'protocol.PlayerHand' },
    { name: 'multiplier', repeated: false, kind: 'int64' },
    { name: 'scores', repeated: true, kind: 'message', message_type: 'protocol.PlayerScore' },
  ],
  'protocol.GameSettlementDTO': [
    { name: 'multiplier', repeated: false, kind: 'int64' },
    { name: 'scores', repeated: true, kind: 'message', message_type: 'protocol.PlayerScore' },
    { name: 'player_hands', repeated: true, kind: 'message', message_type: 'protocol.PlayerHand' },
  ],
  'protocol.GameStartPayload': [
    { name: 'players', repeated: true, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.GameStateDTO': [
    { name: 'players', repeated: true, kind: 'message', message_type: 'protocol.PlayerInfo' },
    { name: 'hand', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'bottom_cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'last_played', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'snapshot_version', repeated: false, kind: 'int64' },
    { name: 'turn_id', repeated: false, kind: 'int64' },
    { name: 'turn_deadline_ms', repeated: false, kind: 'int64' },
    { name: 'server_time_ms', repeated: false, kind: 'int64' },
    { name: 'multiplier', repeated: false, kind: 'int64' },
    { name: 'base_score', repeated: false, kind: 'int64' },
    { name: 'played_cards', repeated: true, kind: 'message', message_type: 'protocol.PlayerPlayedCards' },
    { name: 'settlement', repeated: false, kind: 'message', message_type: 'protocol.GameSettlementDTO' },
  ],
  'protocol.GetLeaderboardPayload': [
    { name: 'offset', repeated: false, kind: 'int64' },
    { name: 'limit', repeated: false, kind: 'int64' },
  ],
  'protocol.LandlordPayload': [
    { name: 'bottom_cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'multiplier', repeated: false, kind: 'int64' },
  ],
  'protocol.LeaderboardEntry': [
    { name: 'rank', repeated: false, kind: 'int64' },
    { name: 'score', repeated: false, kind: 'int64' },
    { name: 'wins', repeated: false, kind: 'int64' },
  ],
  'protocol.LeaderboardResultPayload': [
    { name: 'entries', repeated: true, kind: 'message', message_type: 'protocol.LeaderboardEntry' },
  ],
  'protocol.MatchQueuedPayload': [
    { name: 'deadline_ms', repeated: false, kind: 'int64' },
  ],
  'protocol.Message': [
    { name: 'event', repeated: false, kind: 'message', message_type: 'protocol.EventMeta' },
    { name: 'command', repeated: false, kind: 'message', message_type: 'protocol.CommandMeta' },
  ],
  'protocol.OnlineCountPayload': [
    { name: 'count', repeated: false, kind: 'int64' },
  ],
  'protocol.PingPayload': [
    { name: 'timestamp', repeated: false, kind: 'int64' },
  ],
  'protocol.PlayCardsPayload': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.PlayerHand': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.PlayerInfo': [
    { name: 'seat', repeated: false, kind: 'int64' },
    { name: 'cards_count', repeated: false, kind: 'int64' },
  ],
  'protocol.PlayerJoinedPayload': [
    { name: 'player', repeated: false, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.PlayerOfflinePayload': [
    { name: 'timeout', repeated: false, kind: 'int64' },
  ],
  'protocol.PlayerPlayedCards': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.PlayerScore': [
    { name: 'score', repeated: false, kind: 'int64' },
  ],
  'protocol.PlayTurnPayload': [
    { name: 'timeout', repeated: false, kind: 'int64' },
  ],
  'protocol.PongPayload': [
    { name: 'client_timestamp', repeated: false, kind: 'int64' },
    { name: 'server_timestamp', repeated: false, kind: 'int64' },
  ],
  'protocol.ReconnectedPayload': [
    { name: 'game_state', repeated: false, kind: 'message', message_type: 'protocol.GameStateDTO' },
  ],
  'protocol.RoomCreatedPayload': [
    { name: 'player', repeated: false, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.RoomJoinedPayload': [
    { name: 'player', repeated: false, kind: 'message', message_type: 'protocol.PlayerInfo' },
    { name: 'players', repeated: true, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.RoomListItem': [
    { name: 'player_count', repeated: false, kind: 'int64' },
    { name: 'max_players', repeated: false, kind: 'int64' },
  ],
  'protocol.RoomListResultPayload': [
    { name: 'rooms', repeated: true, kind: 'message', message_type: 'protocol.RoomListItem' },
  ],
  'protocol.StatsResultPayload': [
    { name: 'total_games', repeated: false, kind: 'int64' },
    { name: 'wins', repeated: false, kind: 'int64' },
    { name: 'losses', repeated: false, kind: 'int64' },
    { name: 'landlord_games', repeated: false, kind: 'int64' },
    { name: 'landlord_wins', repeated: false, kind: 'int64' },
    { name: 'farmer_games', repeated: false, kind: 'int64' },
    { name: 'farmer_wins', repeated: false, kind: 'int64' },
    { name: 'score', repeated: false, kind: 'int64' },
    { name: 'rank', repeated: false, kind: 'int64' },
    { name: 'current_streak', repeated: false, kind: 'int64' },
    { name: 'max_win_streak', repeated: false, kind: 'int64' },
  ],
  'protocol.WarningPayload': [
    { name: 'code', repeated: false, kind: 'int64' },
  ],
};

export type ProtocolFieldMetadata =
  | { readonly name: string; readonly repeated: boolean; readonly kind: 'number' | 'string' | 'boolean' | 'bytes' }
  | { readonly name: string; readonly repeated: boolean; readonly kind: 'message'; readonly message_type: string };

export const PROTOCOL_FIELD_METADATA_BY_TYPE: Readonly<Record<string, readonly ProtocolFieldMetadata[]>> = {
  'protocol.BidPayload': [
    { name: 'bid', repeated: false, kind: 'boolean' },
  ],
  'protocol.BidResultPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'bid', repeated: false, kind: 'boolean' },
    { name: 'is_grab', repeated: false, kind: 'boolean' },
    { name: 'multiplier', repeated: false, kind: 'number' },
  ],
  'protocol.BidTurnPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'timeout', repeated: false, kind: 'number' },
    { name: 'is_grab', repeated: false, kind: 'boolean' },
    { name: 'multiplier', repeated: false, kind: 'number' },
  ],
  'protocol.CardInfo': [
    { name: 'suit', repeated: false, kind: 'number' },
    { name: 'rank', repeated: false, kind: 'number' },
    { name: 'color', repeated: false, kind: 'number' },
  ],
  'protocol.CardPlayedPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'cards_left', repeated: false, kind: 'number' },
    { name: 'hand_type', repeated: false, kind: 'string' },
  ],
  'protocol.ChatPayload': [
    { name: 'sender_id', repeated: false, kind: 'string' },
    { name: 'sender_name', repeated: false, kind: 'string' },
    { name: 'content', repeated: false, kind: 'string' },
    { name: 'scope', repeated: false, kind: 'string' },
    { name: 'time', repeated: false, kind: 'number' },
    { name: 'is_system', repeated: false, kind: 'boolean' },
    { name: 'message_id', repeated: false, kind: 'string' },
    { name: 'room_code', repeated: false, kind: 'string' },
    { name: 'game_id', repeated: false, kind: 'string' },
    { name: 'server_time', repeated: false, kind: 'number' },
  ],
  'protocol.CommandAckPayload': [
    { name: 'request_id', repeated: false, kind: 'string' },
    { name: 'command_type', repeated: false, kind: 'number' },
  ],
  'protocol.CommandMeta': [
    { name: 'request_id', repeated: false, kind: 'string' },
    { name: 'expected_game_id', repeated: false, kind: 'string' },
    { name: 'expected_turn_id', repeated: false, kind: 'number' },
  ],
  'protocol.ConnectedPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'reconnect_token', repeated: false, kind: 'string' },
  ],
  'protocol.DealCardsPayload': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'bottom_cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.ErrorPayload': [
    { name: 'code', repeated: false, kind: 'number' },
    { name: 'message', repeated: false, kind: 'string' },
    { name: 'command_type', repeated: false, kind: 'number' },
    { name: 'request_id', repeated: false, kind: 'string' },
  ],
  'protocol.EventMeta': [
    { name: 'stream_id', repeated: false, kind: 'string' },
    { name: 'event_version', repeated: false, kind: 'number' },
    { name: 'game_id', repeated: false, kind: 'string' },
    { name: 'turn_id', repeated: false, kind: 'number' },
    { name: 'server_time_ms', repeated: false, kind: 'number' },
    { name: 'turn_deadline_ms', repeated: false, kind: 'number' },
  ],
  'protocol.GameOverPayload': [
    { name: 'winner_id', repeated: false, kind: 'string' },
    { name: 'winner_name', repeated: false, kind: 'string' },
    { name: 'is_landlord', repeated: false, kind: 'boolean' },
    { name: 'player_hands', repeated: true, kind: 'message', message_type: 'protocol.PlayerHand' },
    { name: 'multiplier', repeated: false, kind: 'number' },
    { name: 'scores', repeated: true, kind: 'message', message_type: 'protocol.PlayerScore' },
  ],
  'protocol.GameSettlementDTO': [
    { name: 'winner_id', repeated: false, kind: 'string' },
    { name: 'winner_name', repeated: false, kind: 'string' },
    { name: 'winner_is_landlord', repeated: false, kind: 'boolean' },
    { name: 'multiplier', repeated: false, kind: 'number' },
    { name: 'scores', repeated: true, kind: 'message', message_type: 'protocol.PlayerScore' },
    { name: 'player_hands', repeated: true, kind: 'message', message_type: 'protocol.PlayerHand' },
  ],
  'protocol.GameStartPayload': [
    { name: 'players', repeated: true, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.GameStateDTO': [
    { name: 'phase', repeated: false, kind: 'string' },
    { name: 'players', repeated: true, kind: 'message', message_type: 'protocol.PlayerInfo' },
    { name: 'hand', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'bottom_cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'current_turn', repeated: false, kind: 'string' },
    { name: 'last_played', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'last_player_id', repeated: false, kind: 'string' },
    { name: 'must_play', repeated: false, kind: 'boolean' },
    { name: 'can_beat', repeated: false, kind: 'boolean' },
    { name: 'snapshot_version', repeated: false, kind: 'number' },
    { name: 'game_id', repeated: false, kind: 'string' },
    { name: 'bottom_cards_revealed', repeated: false, kind: 'boolean' },
    { name: 'turn_id', repeated: false, kind: 'number' },
    { name: 'turn_deadline_ms', repeated: false, kind: 'number' },
    { name: 'server_time_ms', repeated: false, kind: 'number' },
    { name: 'last_player_name', repeated: false, kind: 'string' },
    { name: 'last_hand_type', repeated: false, kind: 'string' },
    { name: 'is_grab', repeated: false, kind: 'boolean' },
    { name: 'multiplier', repeated: false, kind: 'number' },
    { name: 'base_score', repeated: false, kind: 'number' },
    { name: 'played_cards', repeated: true, kind: 'message', message_type: 'protocol.PlayerPlayedCards' },
    { name: 'settlement', repeated: false, kind: 'message', message_type: 'protocol.GameSettlementDTO' },
  ],
  'protocol.GetLeaderboardPayload': [
    { name: 'type', repeated: false, kind: 'string' },
    { name: 'offset', repeated: false, kind: 'number' },
    { name: 'limit', repeated: false, kind: 'number' },
  ],
  'protocol.HelloPayload': [
    { name: 'protocol_version', repeated: false, kind: 'string' },
    { name: 'client_version', repeated: false, kind: 'string' },
    { name: 'capabilities', repeated: true, kind: 'string' },
    { name: 'client_kind', repeated: false, kind: 'string' },
  ],
  'protocol.JoinRoomPayload': [
    { name: 'room_code', repeated: false, kind: 'string' },
  ],
  'protocol.LandlordPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'bottom_cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
    { name: 'multiplier', repeated: false, kind: 'number' },
  ],
  'protocol.LeaderboardEntry': [
    { name: 'rank', repeated: false, kind: 'number' },
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'score', repeated: false, kind: 'number' },
    { name: 'wins', repeated: false, kind: 'number' },
    { name: 'win_rate', repeated: false, kind: 'number' },
  ],
  'protocol.LeaderboardResultPayload': [
    { name: 'type', repeated: false, kind: 'string' },
    { name: 'entries', repeated: true, kind: 'message', message_type: 'protocol.LeaderboardEntry' },
  ],
  'protocol.MaintenancePayload': [
    { name: 'maintenance', repeated: false, kind: 'boolean' },
  ],
  'protocol.MaintenanceStatusPayload': [
    { name: 'maintenance', repeated: false, kind: 'boolean' },
  ],
  'protocol.MatchCancelledPayload': [
    { name: 'reason', repeated: false, kind: 'string' },
  ],
  'protocol.MatchQueuedPayload': [
    { name: 'deadline_ms', repeated: false, kind: 'number' },
    { name: 'practice', repeated: false, kind: 'boolean' },
  ],
  'protocol.Message': [
    { name: 'type', repeated: false, kind: 'number' },
    { name: 'payload', repeated: false, kind: 'bytes' },
    { name: 'event', repeated: false, kind: 'message', message_type: 'protocol.EventMeta' },
    { name: 'command', repeated: false, kind: 'message', message_type: 'protocol.CommandMeta' },
  ],
  'protocol.NegotiatedPayload': [
    { name: 'protocol_version', repeated: false, kind: 'string' },
    { name: 'server_version', repeated: false, kind: 'string' },
    { name: 'capabilities', repeated: true, kind: 'string' },
    { name: 'client_kind', repeated: false, kind: 'string' },
  ],
  'protocol.OnlineCountPayload': [
    { name: 'count', repeated: false, kind: 'number' },
  ],
  'protocol.PingPayload': [
    { name: 'timestamp', repeated: false, kind: 'number' },
  ],
  'protocol.PlayCardsPayload': [
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.PlayerHand': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.PlayerInfo': [
    { name: 'id', repeated: false, kind: 'string' },
    { name: 'name', repeated: false, kind: 'string' },
    { name: 'seat', repeated: false, kind: 'number' },
    { name: 'ready', repeated: false, kind: 'boolean' },
    { name: 'is_landlord', repeated: false, kind: 'boolean' },
    { name: 'cards_count', repeated: false, kind: 'number' },
    { name: 'online', repeated: false, kind: 'boolean' },
    { name: 'is_bot', repeated: false, kind: 'boolean' },
  ],
  'protocol.PlayerJoinedPayload': [
    { name: 'player', repeated: false, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.PlayerLeftPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
  ],
  'protocol.PlayerOfflinePayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'timeout', repeated: false, kind: 'number' },
  ],
  'protocol.PlayerOnlinePayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
  ],
  'protocol.PlayerPassPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
  ],
  'protocol.PlayerPlayedCards': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'cards', repeated: true, kind: 'message', message_type: 'protocol.CardInfo' },
  ],
  'protocol.PlayerReadyPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'ready', repeated: false, kind: 'boolean' },
  ],
  'protocol.PlayerScore': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'is_landlord', repeated: false, kind: 'boolean' },
    { name: 'score', repeated: false, kind: 'number' },
  ],
  'protocol.PlayTurnPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'timeout', repeated: false, kind: 'number' },
    { name: 'must_play', repeated: false, kind: 'boolean' },
    { name: 'can_beat', repeated: false, kind: 'boolean' },
  ],
  'protocol.PongPayload': [
    { name: 'client_timestamp', repeated: false, kind: 'number' },
    { name: 'server_timestamp', repeated: false, kind: 'number' },
  ],
  'protocol.ProtocolRejectedPayload': [
    { name: 'request_id', repeated: false, kind: 'string' },
    { name: 'reason', repeated: false, kind: 'string' },
    { name: 'supported_protocol_version', repeated: false, kind: 'string' },
    { name: 'min_client_version', repeated: false, kind: 'string' },
  ],
  'protocol.ReconnectedPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'room_code', repeated: false, kind: 'string' },
    { name: 'game_state', repeated: false, kind: 'message', message_type: 'protocol.GameStateDTO' },
    { name: 'reconnect_token', repeated: false, kind: 'string' },
  ],
  'protocol.ReconnectPayload': [
    { name: 'token', repeated: false, kind: 'string' },
    { name: 'player_id', repeated: false, kind: 'string' },
  ],
  'protocol.RoomCreatedPayload': [
    { name: 'room_code', repeated: false, kind: 'string' },
    { name: 'player', repeated: false, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.RoomJoinedPayload': [
    { name: 'room_code', repeated: false, kind: 'string' },
    { name: 'player', repeated: false, kind: 'message', message_type: 'protocol.PlayerInfo' },
    { name: 'players', repeated: true, kind: 'message', message_type: 'protocol.PlayerInfo' },
  ],
  'protocol.RoomLeftPayload': [
    { name: 'room_code', repeated: false, kind: 'string' },
  ],
  'protocol.RoomListItem': [
    { name: 'room_code', repeated: false, kind: 'string' },
    { name: 'player_count', repeated: false, kind: 'number' },
    { name: 'max_players', repeated: false, kind: 'number' },
  ],
  'protocol.RoomListResultPayload': [
    { name: 'rooms', repeated: true, kind: 'message', message_type: 'protocol.RoomListItem' },
  ],
  'protocol.StatsResultPayload': [
    { name: 'player_id', repeated: false, kind: 'string' },
    { name: 'player_name', repeated: false, kind: 'string' },
    { name: 'total_games', repeated: false, kind: 'number' },
    { name: 'wins', repeated: false, kind: 'number' },
    { name: 'losses', repeated: false, kind: 'number' },
    { name: 'win_rate', repeated: false, kind: 'number' },
    { name: 'landlord_games', repeated: false, kind: 'number' },
    { name: 'landlord_wins', repeated: false, kind: 'number' },
    { name: 'farmer_games', repeated: false, kind: 'number' },
    { name: 'farmer_wins', repeated: false, kind: 'number' },
    { name: 'score', repeated: false, kind: 'number' },
    { name: 'rank', repeated: false, kind: 'number' },
    { name: 'current_streak', repeated: false, kind: 'number' },
    { name: 'max_win_streak', repeated: false, kind: 'number' },
  ],
  'protocol.WarningPayload': [
    { name: 'code', repeated: false, kind: 'number' },
    { name: 'message', repeated: false, kind: 'string' },
  ],
};
