#!/usr/bin/env bash

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

export LOAD_TEST_CONNECTIONS="${SOAK_CONNECTIONS:-500}"
export LOAD_TEST_CONNECT_CONCURRENCY="${SOAK_CONNECT_CONCURRENCY:-20}"
export LOAD_TEST_DURATION="${SOAK_DURATION:-15m}"
export LOAD_TEST_COOLDOWN="${SOAK_COOLDOWN:-10s}"
export LOAD_TEST_RECONNECTS="${SOAK_RECONNECTS:-50}"
export LOAD_TEST_ROOM_OPERATIONS="${SOAK_ROOM_OPERATIONS:-25}"
export LOAD_TEST_MATCH_OPERATIONS="${SOAK_MATCH_OPERATIONS:-10}"
export LOAD_TEST_MATCH_TIMEOUTS="${SOAK_MATCH_TIMEOUTS:-1}"
export LOAD_TEST_JSON_OUT="${SOAK_JSON_OUT:-artifacts/soak/soak-test.json}"
export LOAD_TEST_MARKDOWN_OUT="${SOAK_MARKDOWN_OUT:-artifacts/soak/soak-test.md}"
export LOAD_TEST_MAX_REDIS_ERRORS="${SOAK_MAX_REDIS_ERRORS:-0}"
export LOAD_TEST_MAX_FINAL_CONNECTIONS_DELTA="${SOAK_MAX_FINAL_CONNECTIONS_DELTA:-0}"
export LOAD_TEST_MAX_FINAL_GOROUTINES_DELTA="${SOAK_MAX_FINAL_GOROUTINES_DELTA:-10}"

exec "$repo_root/scripts/run-load-test.sh" "$@"
